import { Shield } from 'lucide-react';

interface ExportFooterProps {
  /** Whether to show a compact version for space-constrained exports */
  compact?: boolean;
  /** Additional CSS classes */
  className?: string;
}

/**
 * Footer disclaimer for all PDF exports and generated documents.
 * Must be included on all exported content to ensure legal compliance.
 */
export function ExportFooter({ compact = false, className = '' }: ExportFooterProps) {
  if (compact) {
    return (
      <div className={`text-center text-xs text-gray-500 mt-6 pt-4 border-t border-gray-200 ${className}`}>
        <p>
          Generated by Vet Claim Support | Educational tool only. Not affiliated with the VA. Does not provide legal or medical advice.
        </p>
      </div>
    );
  }

  return (
    <div className={`mt-8 pt-6 border-t border-gray-200 ${className}`}>
      <div className="flex items-start gap-3">
        <Shield className="h-5 w-5 text-gray-400 shrink-0 mt-0.5" />
        <div className="space-y-2">
          <p className="text-sm font-medium text-gray-700">
            Generated by Vet Claim Support
          </p>
          <p className="text-xs text-gray-500 leading-relaxed">
            This document is for educational and personal preparation purposes only.
            It does not constitute legal or medical advice. The information provided
            is intended to help you organize and prepare for your VA disability claim.
          </p>
          <p className="text-xs text-gray-500">
            Not affiliated with the U.S. Department of Veterans Affairs.
          </p>
        </div>
      </div>
    </div>
  );
}

/**
 * Short disclaimer text for inline use in documents.
 */
export const SHORT_DISCLAIMER =
  "Educational tool only. Not affiliated with the VA. Does not provide legal or medical advice.";

/**
 * Full disclaimer text for legal documents and comprehensive exports.
 */
export const FULL_DISCLAIMER = `Vet Claim Support is an educational tool designed to help veterans understand and navigate the VA disability claims process. This app does not provide legal advice, medical advice, or representation before the Department of Veterans Affairs.

We are not attorneys, accredited claims agents, or affiliated with the U.S. Department of Veterans Affairs in any way.

The information provided is for educational and organizational purposes only. For legal advice regarding your VA claim, please consult with a VA-accredited attorney or claims agent.`;
