import { Shield } from 'lucide-react';

interface ExportFooterProps {
  /** Whether to show a compact version for space-constrained exports */
  compact?: boolean;
  /** Additional CSS classes */
  className?: string;
}

/**
 * Footer disclaimer for all PDF exports and generated documents.
 * Must be included on all exported content to ensure legal compliance.
 */
export function ExportFooter({ compact = false, className = '' }: ExportFooterProps) {
  if (compact) {
    return (
      <div className={`text-center text-xs text-gray-500 mt-6 pt-4 border-t border-gray-200 ${className}`}>
        <p>
          Generated by Vet Claim Support | Educational tool only. Not affiliated with the VA. Does not provide legal or medical advice.
        </p>
      </div>
    );
  }

  return (
    <div className={`mt-8 pt-6 border-t border-gray-200 ${className}`}>
      <div className="flex items-start gap-3">
        <Shield className="h-5 w-5 text-gray-400 shrink-0 mt-0.5" />
        <div className="space-y-2">
          <p className="text-sm font-medium text-gray-700">
            Generated by Vet Claim Support
          </p>
          <p className="text-xs text-gray-500 leading-relaxed">
            This document is for educational and organizational purposes only.
            It does not constitute legal advice, medical advice, or professional representation.
            AI-generated content may contain errors &mdash; verify all information before submission.
            You are solely responsible for the accuracy of any information submitted to the VA.
          </p>
          <p className="text-xs text-gray-500">
            Not affiliated with, endorsed by, or connected to the U.S. Department of Veterans Affairs.
            For accredited representation, consult va.gov/ogc/apps/accreditation.
          </p>
        </div>
      </div>
    </div>
  );
}

/**
 * Short disclaimer text for inline use in documents.
 */
export const SHORT_DISCLAIMER =
  "Educational tool only. Not affiliated with the VA. Not legal or medical advice. Verify all information before submission.";

/**
 * Full disclaimer text for legal documents and comprehensive exports.
 */
export const FULL_DISCLAIMER = `DISCLAIMER: Vet Claim Support is an educational and organizational tool. It is NOT affiliated with, endorsed by, or connected to the U.S. Department of Veterans Affairs. This document does not constitute legal advice, medical advice, or professional representation. We are not attorneys, VA-accredited claims agents, or medical professionals. AI-generated content may contain errors — verify all information before submission. You are solely responsible for the accuracy of any information submitted to the VA. For accredited representation, consult va.gov/ogc/apps/accreditation.`;
