import { useState, useCallback, useRef } from 'react';
import { useAICacheStore } from '@/store/useAICacheStore';

export function useCaseLaw() {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const abortRef = useRef<AbortController | null>(null);
  const { getCache, setCache } = useAICacheStore();

  const getCaseLaw = useCallback(async (
    conditionName: string,
    claimType: string,
    evidence: string[]
  ): Promise<string | null> => {
    setError(null);

    const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
    if (!apiKey) {
      setError('AI features require a Gemini API key. Add VITE_GEMINI_API_KEY to your environment.');
      return null;
    }

    // Check cache
    const cacheKey = `CASE_LAW:${conditionName}:${claimType}:${evidence.slice(0, 3).join(',')}`.substring(0, 200);
    const cached = getCache(cacheKey);
    if (cached) return cached;

    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;

    setIsLoading(true);
    try {
      const prompt = `You are an expert in VA disability case law and Board of Veterans' Appeals (BVA) decisions.

For the condition: ${conditionName}
Claim type: ${claimType}
Evidence available: ${evidence.join(', ')}

Provide 3-5 relevant BVA decisions or Federal Circuit cases that could strengthen this claim. For each case:
1. Case citation (e.g., "Smith v. Wilkie, 2020 U.S. App. Vet. Claims LEXIS 1234")
2. One sentence summary of the ruling
3. Why it's relevant to this specific claim
4. The key legal principle established

Focus on:
- Cases where the veteran prevailed
- Cases establishing beneficial legal precedents
- Cases relevant to the specific condition and claim type
- Cases from the last 10 years when possible

CRITICAL DISCLAIMER: Include this at the end: "WARNING: These case law citations were generated by AI and have NOT been verified. AI frequently fabricates case names, citations, and legal holdings. You MUST independently verify every citation using Google Scholar (scholar.google.com) or official VA/court databases before including them in any submission. Submitting fabricated citations may result in claim denial or fraud charges."`;

      const res = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          signal: controller.signal,
          body: JSON.stringify({
            contents: [{ parts: [{ text: prompt }] }],
          }),
        }
      );

      if (!res.ok) {
        throw new Error(`Gemini API error: ${res.status}`);
      }

      const data = await res.json();
      const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!text) {
        throw new Error('Unexpected response format');
      }

      setCache(cacheKey, text, 'EXAMINER_PERSONA');
      return text;
    } catch (err: unknown) {
      if (err instanceof DOMException && err.name === 'AbortError') {
        return null;
      }
      console.error('[useCaseLaw]', err);
      setError('Failed to generate case law references. Please try again.');
      return null;
    } finally {
      setIsLoading(false);
    }
  }, [getCache, setCache]);

  const cancel = useCallback(() => {
    abortRef.current?.abort();
  }, []);

  return { getCaseLaw, isLoading, cancel, error };
}
