import { useState, useMemo, useRef, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { safeFormatDate } from '@/utils/dateUtils';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Separator } from '@/components/ui/separator';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import {
  Share2, Download, Shield, AlertTriangle, Copy,
  CheckCircle2, Star, Loader2,
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { ToastAction } from '@/components/ui/toast';
import { saveToVault } from '@/utils/vaultAutoSave';
import useAppStore from '@/store/useAppStore';
import { useProfileStore } from '@/store/useProfileStore';
import { getConditionDisplayName } from '@/utils/conditionResolver';
import { COMP_RATES_2026 } from '@/data/compRates2026';
import { PageContainer } from '@/components/PageContainer';
import { combineRatings } from '@/utils/vaMath';

export default function ShareableSummary() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const userConditions = useAppStore((s) => s.userConditions);
  const deadlines = useAppStore((s) => s.deadlines);
  const profile = useProfileStore();
  const summaryRef = useRef<HTMLDivElement>(null);

  const [copied, setCopied] = useState(false);
  const [sharing, setSharing] = useState(false);
  const [includeConditions, setIncludeConditions] = useState(true);
  const [includeCompensation, setIncludeCompensation] = useState(true);
  const [includeDeadlines, setIncludeDeadlines] = useState(true);

  const summary = useMemo(() => {
    const conditions = userConditions.map(uc => {
      return {
        name: getConditionDisplayName(uc),
        rating: uc.rating,
        status: uc.claimStatus,
        serviceConnected: uc.serviceConnected,
      };
    });

    const ratings = conditions
      .filter(c => c.rating !== undefined && c.rating > 0)
      .map(c => c.rating!);

    const combinedRating = combineRatings(ratings);
    const monthlyComp = COMP_RATES_2026[combinedRating] || 0;
    const annualComp = monthlyComp * 12;

    const activeDeadlines = deadlines
      .filter(d => !d.completed)
      .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

    return {
      conditions,
      combinedRating,
      monthlyComp,
      annualComp,
      totalConditions: conditions.length,
      pendingConditions: conditions.filter(c => c.status === 'pending').length,
      approvedConditions: conditions.filter(c => c.status === 'approved').length,
      activeDeadlines,
      branch: profile.branch,
      claimType: profile.claimType,
      generatedAt: new Date().toLocaleDateString('en-US', {
        month: 'long',
        day: 'numeric',
        year: 'numeric',
      }),
    };
  }, [userConditions, deadlines, profile.branch, profile.claimType]);

  const generateTextSummary = useCallback(() => {
    const lines: string[] = [];
    lines.push('═══════════════════════════════════════');
    lines.push('       VA CLAIMS SUMMARY');
    lines.push('       Generated by Vet Claim Support');
    lines.push('═══════════════════════════════════════');
    lines.push('');
    lines.push('⚠️  NOT AN OFFICIAL VA DOCUMENT');
    lines.push('    For personal planning purposes only.');
    lines.push('');

    if (summary.branch) {
      lines.push(`Branch: ${summary.branch}`);
    }
    if (summary.claimType) {
      lines.push(`Claim Type: ${summary.claimType}`);
    }
    lines.push(`Generated: ${summary.generatedAt}`);
    lines.push('');

    lines.push(`Combined Rating: ${summary.combinedRating}%`);
    if (includeCompensation && summary.monthlyComp > 0) {
      lines.push(`Est. Monthly Compensation: $${summary.monthlyComp.toLocaleString('en-US', { minimumFractionDigits: 2 })}`);
      lines.push(`Est. Annual Compensation: $${summary.annualComp.toLocaleString('en-US', { minimumFractionDigits: 2 })}`);
      lines.push('(2026 rates, no dependents, tax-free)');
    }
    lines.push('');

    if (includeConditions && summary.conditions.length > 0) {
      lines.push('── CONDITIONS ──');
      summary.conditions.forEach(c => {
        const ratingStr = c.rating !== undefined ? `${c.rating}%` : 'Not rated';
        const statusStr = c.status === 'approved' ? '✓' : c.status === 'pending' ? '⏳' : c.status === 'denied' ? '✗' : '↩';
        lines.push(`  ${statusStr} ${c.name} — ${ratingStr}`);
      });
      lines.push('');
      lines.push(`Total: ${summary.totalConditions} | Approved: ${summary.approvedConditions} | Pending: ${summary.pendingConditions}`);
      lines.push('');
    }

    if (includeDeadlines && summary.activeDeadlines.length > 0) {
      lines.push('── UPCOMING DEADLINES ──');
      summary.activeDeadlines.forEach(d => {
        lines.push(`  📅 ${d.title} — ${safeFormatDate(d.date)}`);
      });
      lines.push('');
    }

    lines.push('───────────────────────────────────────');
    lines.push('Generated with Vet Claim Support');
    lines.push('vetclaimsupport.com');

    return lines.join('\n');
  }, [summary, includeConditions, includeCompensation, includeDeadlines]);

  const handleCopyText = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(generateTextSummary());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = generateTextSummary();
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [generateTextSummary]);

  const handleShare = useCallback(async () => {
    setSharing(true);
    try {
      if (navigator.share) {
        await navigator.share({
          title: 'VA Claims Summary',
          text: generateTextSummary(),
        });
      } else {
        // Fallback to copy
        await handleCopyText();
      }
    } catch (err) {
      // User cancelled share or share not supported
      if ((err as Error).name !== 'AbortError') {
        await handleCopyText();
      }
    } finally {
      setSharing(false);
    }
  }, [generateTextSummary, handleCopyText]);

  const handleDownloadText = useCallback(async () => {
    const text = generateTextSummary();
    const filename = `va-claims-summary-${new Date().toISOString().split('T')[0]}.txt`;
    const blob = new Blob([text], { type: 'text/plain' });

    if (navigator.share && navigator.canShare?.({ files: [new File([blob], filename)] })) {
      try {
        await navigator.share({ files: [new File([blob], filename, { type: 'text/plain' })] });
      } catch { /* cancelled */ }
    } else {
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }

    saveToVault({
      documentType: 'shareable-summary',
      condition: '',
      title: 'Claims Summary',
      content: text,
      fileName: filename,
    }).then(() => {
      toast({
        title: 'Saved to Vault',
        action: <ToastAction altText="View in Vault" onClick={() => navigate('/claims/vault')}>View</ToastAction>,
      });
    }).catch(() => {});
  }, [generateTextSummary, toast, navigate]);

  return (
    <PageContainer className="py-8 space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-center gap-4">
          <div className="p-3 rounded-2xl bg-gradient-to-br from-primary to-primary/80 text-primary-foreground shadow-lg">
            <Share2 className="h-6 w-6" />
          </div>
          <div>
            <h1 className="text-2xl font-bold">Claims Summary</h1>
            <p className="text-muted-foreground">Share or export your claims overview</p>
          </div>
        </div>
      </div>

      {/* Disclaimer */}
      <Alert className="border-warning/30 bg-warning/5">
        <AlertTriangle className="h-4 w-4 text-warning" />
        <AlertDescription className="text-warning text-sm">
          This is <strong>NOT an official VA document</strong>. This summary is generated from data you entered
          into Vet Claim Support for personal planning and organization purposes only.
        </AlertDescription>
      </Alert>

      {/* Summary Card Preview */}
      <Card className="border-0 shadow-xl overflow-hidden" ref={summaryRef}>
        <div className="bg-gradient-to-r from-gray-900 to-gray-800 p-6 text-white">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs text-white/60 uppercase tracking-wider">VA Claims Summary</p>
              <h2 className="text-3xl font-bold mt-1">{summary.combinedRating}%</h2>
              <p className="text-white/60 text-sm">Combined Rating</p>
            </div>
            <div className="text-right">
              {summary.monthlyComp > 0 && (
                <>
                  <p className="text-2xl font-bold text-success">
                    ${summary.monthlyComp.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                  </p>
                  <p className="text-white/60 text-sm">Est. Monthly (2026)</p>
                </>
              )}
            </div>
          </div>
        </div>

        <CardContent className="p-6 space-y-5">
          {/* Quick Stats */}
          <div className="grid grid-cols-3 gap-4">
            <div className="text-center p-3 rounded-lg bg-muted/50">
              <p className="text-2xl font-bold">{summary.totalConditions}</p>
              <p className="text-xs text-muted-foreground">Conditions</p>
            </div>
            <div className="text-center p-3 rounded-lg bg-success/5">
              <p className="text-2xl font-bold text-success">{summary.approvedConditions}</p>
              <p className="text-xs text-muted-foreground">Approved</p>
            </div>
            <div className="text-center p-3 rounded-lg bg-warning/5">
              <p className="text-2xl font-bold text-warning">{summary.pendingConditions}</p>
              <p className="text-xs text-muted-foreground">Pending</p>
            </div>
          </div>

          {/* Conditions List */}
          {includeConditions && summary.conditions.length > 0 && (
            <>
              <Separator />
              <div>
                <h3 className="text-sm font-semibold mb-3">Conditions</h3>
                <div className="space-y-2">
                  {summary.conditions.map((c, i) => (
                    <div key={i} className="flex items-center justify-between py-2 px-3 rounded-lg bg-muted/30">
                      <div className="flex items-center gap-2 min-w-0">
                        {c.status === 'approved' && <CheckCircle2 className="h-4 w-4 text-success flex-shrink-0" />}
                        {c.status === 'pending' && <Star className="h-4 w-4 text-warning flex-shrink-0" />}
                        <span className="text-sm truncate">{c.name}</span>
                      </div>
                      <Badge variant="outline" className="text-xs flex-shrink-0 ml-2">
                        {c.rating !== undefined ? `${c.rating}%` : 'N/A'}
                      </Badge>
                    </div>
                  ))}
                </div>
              </div>
            </>
          )}

          {/* Deadlines */}
          {includeDeadlines && summary.activeDeadlines.length > 0 && (
            <>
              <Separator />
              <div>
                <h3 className="text-sm font-semibold mb-3">Upcoming Deadlines</h3>
                <div className="space-y-2">
                  {summary.activeDeadlines.slice(0, 3).map((d, i) => (
                    <div key={i} className="flex items-center justify-between py-2 px-3 rounded-lg bg-muted/30">
                      <span className="text-sm">{d.title}</span>
                      <span className="text-xs text-muted-foreground">
                        {safeFormatDate(d.date)}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            </>
          )}

          {/* Footer */}
          <Separator />
          <div className="flex items-center justify-between text-xs text-muted-foreground">
            <span>Generated {summary.generatedAt}</span>
            <span className="flex items-center gap-1">
              <Shield className="h-3 w-3" />
              Not an official VA document
            </span>
          </div>
        </CardContent>
      </Card>

      {/* Customization */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Customize Summary</CardTitle>
          <CardDescription>Choose what to include in your export</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center justify-between">
            <Label htmlFor="include-conditions" className="text-sm">Include conditions list</Label>
            <Switch id="include-conditions" checked={includeConditions} onCheckedChange={setIncludeConditions} />
          </div>
          <div className="flex items-center justify-between">
            <Label htmlFor="include-comp" className="text-sm">Include compensation estimate</Label>
            <Switch id="include-comp" checked={includeCompensation} onCheckedChange={setIncludeCompensation} />
          </div>
          <div className="flex items-center justify-between">
            <Label htmlFor="include-deadlines" className="text-sm">Include upcoming deadlines</Label>
            <Switch id="include-deadlines" checked={includeDeadlines} onCheckedChange={setIncludeDeadlines} />
          </div>
        </CardContent>
      </Card>

      {/* Actions */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        <Button
          onClick={handleShare}
          disabled={sharing}
          className="w-full"
        >
          {sharing ? (
            <Loader2 className="h-4 w-4 mr-2 animate-spin" />
          ) : (
            <Share2 className="h-4 w-4 mr-2" />
          )}
          Share
        </Button>
        <Button variant="outline" onClick={handleCopyText} className="w-full">
          {copied ? (
            <CheckCircle2 className="h-4 w-4 mr-2 text-success" />
          ) : (
            <Copy className="h-4 w-4 mr-2" />
          )}
          {copied ? 'Copied!' : 'Copy Text'}
        </Button>
        <Button variant="outline" onClick={handleDownloadText} className="w-full">
          <Download className="h-4 w-4 mr-2" />
          Download
        </Button>
      </div>
    </PageContainer>
  );
}
