/**
 * PDF Report Generator for Vet Claim Support
 * Generates a comprehensive claim summary as a formatted document
 */

interface ReportSection {
  title: string;
  content: string[];
}

interface ReportData {
  generatedAt: Date;
  sections: ReportSection[];
  metadata?: Record<string, string>;
}

// Generate HTML content for the report
function generateReportHTML(data: ReportData): string {
  const formatDate = (date: Date) =>
    date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

  const sectionsHTML = data.sections
    .map(
      (section) => `
    <div class="section">
      <h2>${section.title}</h2>
      ${section.content.map((item) => `<p>${item}</p>`).join('')}
    </div>
  `
    )
    .join('');

  const metadataHTML = data.metadata
    ? `
    <div class="metadata">
      ${Object.entries(data.metadata)
        .map(([key, value]) => `<p><strong>${key}:</strong> ${value}</p>`)
        .join('')}
    </div>
  `
    : '';

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>VA Claim Summary Report</title>
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          line-height: 1.6;
          color: #1a1a1a;
          padding: 40px;
          max-width: 800px;
          margin: 0 auto;
        }
        .header {
          text-align: center;
          padding-bottom: 30px;
          border-bottom: 2px solid #2563eb;
          margin-bottom: 30px;
        }
        .header h1 {
          color: #2563eb;
          font-size: 24px;
          margin-bottom: 10px;
        }
        .header .date {
          color: #666;
          font-size: 14px;
        }
        .disclaimer {
          background: #fef3c7;
          border: 1px solid #f59e0b;
          border-radius: 8px;
          padding: 15px;
          margin-bottom: 30px;
          font-size: 12px;
          color: #92400e;
        }
        .section {
          margin-bottom: 30px;
          page-break-inside: avoid;
        }
        .section h2 {
          color: #2563eb;
          font-size: 18px;
          border-bottom: 1px solid #e5e7eb;
          padding-bottom: 8px;
          margin-bottom: 15px;
        }
        .section p {
          margin-bottom: 10px;
          font-size: 14px;
        }
        .metadata {
          background: #f3f4f6;
          padding: 15px;
          border-radius: 8px;
          margin-bottom: 30px;
          font-size: 13px;
        }
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          text-align: center;
          font-size: 12px;
          color: #666;
        }
        @media print {
          body {
            padding: 20px;
          }
          .section {
            page-break-inside: avoid;
          }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>VA Disability Claim Summary</h1>
        <p class="date">Generated on ${formatDate(data.generatedAt)}</p>
      </div>

      <div class="disclaimer">
        <strong>IMPORTANT:</strong> This report is for personal reference only and is not intended
        as legal or medical advice. Consult with a Veterans Service Officer (VSO) or VA-accredited
        attorney for official guidance on your claim.
      </div>

      ${metadataHTML}
      ${sectionsHTML}

      <div class="footer">
        <p>Generated by Vet Claim Support</p>
        <p>This document is for personal use only.</p>
      </div>
    </body>
    </html>
  `;
}

// Open print dialog with report
export function printReport(data: ReportData): void {
  const html = generateReportHTML(data);
  const printWindow = window.open('', '_blank');

  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.onload = () => {
      printWindow.print();
    };
  }
}

// Download report as HTML file
export function downloadReportAsHTML(data: ReportData, filename = 'claim-summary.html'): void {
  const html = generateReportHTML(data);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// Generate report from user data
export function generateClaimReport(userData: {
  symptoms?: Array<{ date: string; description: string; severity: number }>;
  medications?: Array<{ name: string; dosage: string; frequency: string }>;
  documents?: Array<{ name: string; type: string; date: string }>;
  conditions?: Array<{ name: string; status: string }>;
  buddyContacts?: Array<{ name: string; status: string }>;
  serviceHistory?: { branch?: string; startDate?: string; endDate?: string };
}): ReportData {
  const sections: ReportSection[] = [];

  // Service History
  if (userData.serviceHistory) {
    const { branch, startDate, endDate } = userData.serviceHistory;
    sections.push({
      title: 'Service History',
      content: [
        branch ? `Branch: ${branch}` : 'Branch: Not specified',
        startDate ? `Service Start: ${startDate}` : '',
        endDate ? `Service End: ${endDate}` : '',
      ].filter(Boolean),
    });
  }

  // Conditions
  if (userData.conditions && userData.conditions.length > 0) {
    sections.push({
      title: 'Claimed Conditions',
      content: userData.conditions.map(
        (c) => `• ${c.name} (Status: ${c.status})`
      ),
    });
  }

  // Symptoms
  if (userData.symptoms && userData.symptoms.length > 0) {
    const recentSymptoms = userData.symptoms.slice(0, 10);
    sections.push({
      title: 'Recent Symptom Entries',
      content: recentSymptoms.map(
        (s) => `• ${s.date}: ${s.description} (Severity: ${s.severity}/10)`
      ),
    });
  }

  // Medications
  if (userData.medications && userData.medications.length > 0) {
    sections.push({
      title: 'Current Medications',
      content: userData.medications.map(
        (m) => `• ${m.name} - ${m.dosage}, ${m.frequency}`
      ),
    });
  }

  // Documents
  if (userData.documents && userData.documents.length > 0) {
    sections.push({
      title: 'Supporting Documents',
      content: userData.documents.map(
        (d) => `• ${d.name} (${d.type}) - ${d.date}`
      ),
    });
  }

  // Buddy Statements
  if (userData.buddyContacts && userData.buddyContacts.length > 0) {
    sections.push({
      title: 'Buddy Statement Contacts',
      content: userData.buddyContacts.map(
        (b) => `• ${b.name} - ${b.status}`
      ),
    });
  }

  // Add summary section
  sections.push({
    title: 'Next Steps',
    content: [
      '1. Review all entries for accuracy and completeness',
      '2. Gather any missing documentation',
      '3. Schedule appointment with VSO to review claim',
      '4. Complete VA Form 21-526EZ',
      '5. Submit claim through VA.gov or with VSO assistance',
    ],
  });

  return {
    generatedAt: new Date(),
    sections,
    metadata: {
      'Total Symptom Entries': String(userData.symptoms?.length ?? 0),
      'Total Documents': String(userData.documents?.length ?? 0),
      'Claimed Conditions': String(userData.conditions?.length ?? 0),
      'Buddy Contacts': String(userData.buddyContacts?.length ?? 0),
    },
  };
}
