// PDF Export Utilities for Vet Claim Support
import type jsPDFType from 'jspdf';
import type { ServiceEntry, MedicalVisit, SymptomEntry, Medication, Exposure, DocumentItem, BuddyContact, ClaimsData, ClaimCondition, MigraineEntry, SleepEntry } from '@/types/claims';

const loadJsPDF = async () => {
  const { default: jsPDF } = await import('jspdf');
  return jsPDF;
};

// Duration labels for migraines
const migraineDurations: Record<string, string> = {
  '30min': '30 minutes',
  '1hr': '1 hour',
  '2hrs': '2 hours',
  '4hrs': '4 hours',
  '8hrs': '8 hours',
  '12hrs': '12 hours',
  '24hrs+': '24+ hours',
};

interface PDFExportOptions {
  title: string;
  subtitle?: string;
  generatedDate?: Date;
}

// Colors (matching the app's design tokens)
const colors = {
  primary: [26, 54, 93] as [number, number, number],      // #1a365d
  secondary: [45, 55, 72] as [number, number, number],    // #2d3748
  muted: [113, 128, 150] as [number, number, number],     // #718096
  success: [34, 84, 61] as [number, number, number],      // #22543d
  warning: [116, 66, 16] as [number, number, number],     // #744210
  danger: [155, 44, 44] as [number, number, number],      // #9b2c2c
  border: [226, 232, 240] as [number, number, number],    // #e2e8f0
  background: [247, 250, 252] as [number, number, number], // #f7fafc
  infoBg: [235, 248, 255] as [number, number, number],    // #ebf8ff
  successBg: [198, 246, 213] as [number, number, number], // #c6f6d5
  warningBg: [254, 252, 191] as [number, number, number], // #fefcbf
  dangerBg: [254, 215, 215] as [number, number, number],  // #fed7d7
};

// Helper to add header to each PDF
const addPDFHeader = (doc: jsPDFType, options: PDFExportOptions, yPos: number = 20): number => {
  const date = options.generatedDate || new Date();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(...colors.primary);
  doc.setFont('helvetica', 'bold');
  doc.text(options.title, 20, yPos);
  
  // Underline
  doc.setDrawColor(...colors.primary);
  doc.setLineWidth(0.5);
  doc.line(20, yPos + 3, pageWidth - 20, yPos + 3);
  
  yPos += 12;
  
  // Subtitle
  if (options.subtitle) {
    doc.setFontSize(11);
    doc.setTextColor(...colors.muted);
    doc.setFont('helvetica', 'normal');
    doc.text(options.subtitle, 20, yPos);
    yPos += 6;
  }
  
  // Generated date
  doc.setFontSize(9);
  doc.setTextColor(...colors.muted);
  doc.text(`Generated: ${date.toLocaleDateString()} at ${date.toLocaleTimeString()}`, 20, yPos);
  
  return yPos + 10;
};

// Helper to add footer
const addPDFFooter = (doc: jsPDF) => {
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setDrawColor(...colors.border);
  doc.setLineWidth(0.3);
  doc.line(20, pageHeight - 40, pageWidth - 20, pageHeight - 40);

  doc.setFontSize(8);
  doc.setTextColor(...colors.muted);
  doc.setFont('helvetica', 'bold');
  doc.text('DISCLAIMER', pageWidth / 2, pageHeight - 34, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.text('Generated by Vet Claim Support', pageWidth / 2, pageHeight - 28, { align: 'center' });
  doc.text('This document is for educational and personal preparation purposes only.', pageWidth / 2, pageHeight - 22, { align: 'center' });
  doc.text('It does not constitute legal or medical advice.', pageWidth / 2, pageHeight - 16, { align: 'center' });
  doc.text('Not affiliated with the U.S. Department of Veterans Affairs.', pageWidth / 2, pageHeight - 10, { align: 'center' });
};

// Helper to check for page break
const checkPageBreak = (doc: jsPDFType, yPos: number, neededHeight: number = 40): number => {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (yPos + neededHeight > pageHeight - 45) {
    doc.addPage();
    return 20;
  }
  return yPos;
};

// Helper to draw info box
const drawInfoBox = (doc: jsPDFType, text: string, yPos: number, type: 'info' | 'success' = 'info'): number => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const bgColor = type === 'success' ? colors.successBg : colors.infoBg;
  const borderColor = type === 'success' ? colors.success : colors.primary;
  
  const lines = doc.splitTextToSize(text, pageWidth - 50);
  const boxHeight = lines.length * 5 + 10;
  
  // Background
  doc.setFillColor(...bgColor);
  doc.roundedRect(20, yPos, pageWidth - 40, boxHeight, 2, 2, 'F');
  
  // Left border
  doc.setFillColor(...borderColor);
  doc.rect(20, yPos, 3, boxHeight, 'F');
  
  // Text
  doc.setFontSize(9);
  doc.setTextColor(...colors.secondary);
  doc.text(lines, 28, yPos + 8);
  
  return yPos + boxHeight + 8;
};

// Helper to draw summary box
const drawSummaryBox = (doc: jsPDFType, items: { value: string | number; label: string }[], yPos: number): number => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const boxWidth = (pageWidth - 50) / items.length;
  
  // Background
  doc.setFillColor(...colors.background);
  doc.roundedRect(20, yPos, pageWidth - 40, 35, 2, 2, 'F');
  
  items.forEach((item, index) => {
    const x = 20 + (boxWidth * index) + (boxWidth / 2);
    
    doc.setFontSize(18);
    doc.setTextColor(...colors.primary);
    doc.setFont('helvetica', 'bold');
    doc.text(String(item.value), x, yPos + 18, { align: 'center' });
    
    doc.setFontSize(8);
    doc.setTextColor(...colors.muted);
    doc.setFont('helvetica', 'normal');
    doc.text(item.label, x, yPos + 26, { align: 'center' });
  });
  
  return yPos + 45;
};

// Helper to wrap text properly
const wrapText = (doc: jsPDFType, text: string, maxWidth: number): string[] => {
  return doc.splitTextToSize(text || '', maxWidth);
};

// Service History Export
export const exportServiceHistory = async (entries: ServiceEntry[]) => {
  if (entries.length === 0) {
    alert('No service history entries to export');
    return;
  }

  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const sorted = [...entries].sort((a, b) => new Date(b.startDate).getTime() - new Date(a.startDate).getTime());
  
  let yPos = addPDFHeader(doc, {
    title: 'Service History Record',
    subtitle: 'Military Service Documentation for VA Claims'
  });
  
  yPos = drawInfoBox(doc, 'Service History Documentation: This log documents your duty stations, deployments, and hazardous exposures during military service. This information is critical for establishing service connection for your VA disability claims.', yPos);
  
  // Section header
  doc.setFontSize(14);
  doc.setTextColor(...colors.secondary);
  doc.setFont('helvetica', 'bold');
  doc.text(`Service Record Summary (${entries.length} entries)`, 20, yPos);
  yPos += 10;
  
  sorted.forEach((entry) => {
    yPos = checkPageBreak(doc, yPos, 50);
    
    // Entry box
    doc.setDrawColor(...colors.border);
    doc.setLineWidth(0.3);
    
    const startY = yPos;
    yPos += 5;
    
    // Date range
    doc.setFontSize(11);
    doc.setTextColor(...colors.secondary);
    doc.setFont('helvetica', 'bold');
    const dateRange = `${new Date(entry.startDate).toLocaleDateString()} - ${entry.endDate ? new Date(entry.endDate).toLocaleDateString() : 'Present'}`;
    doc.text(dateRange, 25, yPos);
    yPos += 7;
    
    // Location
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...colors.muted);
    doc.text('Location:', 25, yPos);
    doc.setTextColor(...colors.secondary);
    doc.text(entry.base || 'N/A', 50, yPos);
    yPos += 5;
    
    if (entry.unit) {
      doc.setTextColor(...colors.muted);
      doc.text('Unit:', 25, yPos);
      doc.setTextColor(...colors.secondary);
      doc.text(entry.unit, 50, yPos);
      yPos += 5;
    }
    
    if (entry.afsc) {
      doc.setTextColor(...colors.muted);
      doc.text('AFSC/MOS:', 25, yPos);
      doc.setTextColor(...colors.secondary);
      doc.text(entry.afsc, 50, yPos);
      yPos += 5;
    }
    
    if (entry.duties) {
      doc.setTextColor(...colors.muted);
      doc.text('Duties:', 25, yPos);
      const dutyLines = wrapText(doc, entry.duties, pageWidth - 75);
      doc.setTextColor(...colors.secondary);
      doc.text(dutyLines, 50, yPos);
      yPos += dutyLines.length * 4 + 2;
    }
    
    if (entry.hazards) {
      doc.setFillColor(...colors.dangerBg);
      doc.roundedRect(25, yPos - 2, pageWidth - 50, 12, 1, 1, 'F');
      doc.setTextColor(...colors.danger);
      doc.setFont('helvetica', 'bold');
      doc.text('⚠ Hazards:', 28, yPos + 5);
      doc.setFont('helvetica', 'normal');
      const hazardLines = wrapText(doc, entry.hazards, pageWidth - 85);
      doc.text(hazardLines[0] || '', 55, yPos + 5);
      yPos += 15;
    }
    
    yPos += 3;
    
    // Draw border around entry
    doc.roundedRect(22, startY, pageWidth - 44, yPos - startY, 2, 2, 'S');
    yPos += 5;
  });
  
  addPDFFooter(doc);
  doc.save('service-history.pdf');
};

// Medical Visits Export
export const exportMedicalVisits = async (visits: MedicalVisit[]) => {
  if (visits.length === 0) {
    alert('No medical visits to export');
    return;
  }

  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const sorted = [...visits].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  const withoutSummary = visits.filter(v => !v.gotAfterVisitSummary).length;
  
  let yPos = addPDFHeader(doc, {
    title: 'Medical Visits Log',
    subtitle: 'Healthcare Documentation for VA Claims'
  });
  
  yPos = drawSummaryBox(doc, [
    { value: visits.length, label: 'Total Visits' },
    { value: visits.filter(v => v.gotAfterVisitSummary).length, label: 'With Summary' },
    { value: withoutSummary, label: 'Missing Summaries' }
  ], yPos);
  
  yPos = drawInfoBox(doc, 'Documentation Tip: Medical records are critical for VA claims. Ensure you have copies of all After-Visit Summaries and that your symptoms were accurately documented by providers.', yPos);
  
  doc.setFontSize(14);
  doc.setTextColor(...colors.secondary);
  doc.setFont('helvetica', 'bold');
  doc.text(`Medical Visit Log (${visits.length} entries)`, 20, yPos);
  yPos += 10;
  
  sorted.forEach((visit) => {
    yPos = checkPageBreak(doc, yPos, 45);
    
    const startY = yPos;
    yPos += 5;
    
    // Header row
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.secondary);
    doc.text(new Date(visit.date).toLocaleDateString(), 25, yPos);
    
    // Visit type badge
    doc.setFillColor(...colors.infoBg);
    doc.roundedRect(100, yPos - 4, 40, 6, 1, 1, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...colors.primary);
    doc.text(visit.visitType || 'Visit', 120, yPos, { align: 'center' });
    yPos += 7;
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    
    const fields = [
      { label: 'Reason', value: visit.reason },
      { label: 'Location', value: visit.location },
      { label: 'Provider', value: visit.provider },
      { label: 'Diagnosis', value: visit.diagnosis },
      { label: 'Treatment', value: visit.treatment },
    ];
    
    fields.forEach(field => {
      if (field.value) {
        doc.setTextColor(...colors.muted);
        doc.text(`${field.label}:`, 25, yPos);
        const lines = wrapText(doc, field.value, pageWidth - 75);
        doc.setTextColor(...colors.secondary);
        doc.text(lines, 55, yPos);
        yPos += lines.length * 4 + 2;
      }
    });
    
    // After-visit summary badge
    doc.setTextColor(...colors.muted);
    doc.text('After-Visit Summary:', 25, yPos);
    const hasAVS = visit.gotAfterVisitSummary;
    doc.setFillColor(...(hasAVS ? colors.successBg : colors.dangerBg));
    doc.roundedRect(70, yPos - 3, 15, 5, 1, 1, 'F');
    doc.setFontSize(7);
    doc.setTextColor(...(hasAVS ? colors.success : colors.danger));
    doc.text(hasAVS ? 'Yes' : 'No', 77.5, yPos, { align: 'center' });
    yPos += 8;
    
    doc.setDrawColor(...colors.border);
    doc.roundedRect(22, startY, pageWidth - 44, yPos - startY, 2, 2, 'S');
    yPos += 5;
  });
  
  addPDFFooter(doc);
  doc.save('medical-visits.pdf');
};

// Symptoms Journal Export
export const exportSymptoms = async (symptoms: SymptomEntry[]) => {
  if (symptoms.length === 0) {
    alert('No symptoms to export');
    return;
  }

  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const sorted = [...symptoms].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  const avgSeverity = symptoms.length > 0 
    ? (symptoms.reduce((sum, s) => sum + s.severity, 0) / symptoms.length).toFixed(1)
    : '0';
  
  let yPos = addPDFHeader(doc, {
    title: 'Symptoms Journal',
    subtitle: 'Symptom Documentation for VA Claims'
  });
  
  yPos = drawSummaryBox(doc, [
    { value: symptoms.length, label: 'Total Entries' },
    { value: avgSeverity, label: 'Avg. Severity' },
    { value: symptoms.filter(s => s.severity >= 7).length, label: 'Severe (7+)' }
  ], yPos);
  
  yPos = drawInfoBox(doc, 'VA Rating Tip: Consistent documentation of symptom frequency, severity, and impact on daily life helps establish the current level of disability for rating purposes.', yPos);
  
  doc.setFontSize(14);
  doc.setTextColor(...colors.secondary);
  doc.setFont('helvetica', 'bold');
  doc.text(`Symptoms Journal (${symptoms.length} entries)`, 20, yPos);
  yPos += 10;
  
  sorted.forEach((symptom) => {
    yPos = checkPageBreak(doc, yPos, 40);
    
    const startY = yPos;
    yPos += 5;
    
    // Header
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.secondary);
    doc.text(new Date(symptom.date).toLocaleDateString(), 25, yPos);
    
    // Severity badge
    const severity = symptom.severity || 0;
    const severityColor = severity <= 3 ? colors.successBg : severity <= 6 ? colors.warningBg : colors.dangerBg;
    const severityTextColor = severity <= 3 ? colors.success : severity <= 6 ? colors.warning : colors.danger;
    doc.setFillColor(...severityColor);
    doc.roundedRect(100, yPos - 4, 20, 6, 1, 1, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...severityTextColor);
    doc.text(`${severity}/10`, 110, yPos, { align: 'center' });
    yPos += 7;
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    
    const fields = [
      { label: 'Symptom', value: symptom.symptom },
      { label: 'Body Area', value: symptom.bodyArea },
      { label: 'Frequency', value: symptom.frequency },
      { label: 'Daily Impact', value: symptom.dailyImpact },
      { label: 'Notes', value: symptom.notes },
    ];
    
    fields.forEach(field => {
      if (field.value) {
        doc.setTextColor(...colors.muted);
        doc.text(`${field.label}:`, 25, yPos);
        const lines = wrapText(doc, field.value, pageWidth - 70);
        doc.setTextColor(...colors.secondary);
        doc.text(lines, 55, yPos);
        yPos += lines.length * 4 + 2;
      }
    });
    
    yPos += 3;
    doc.setDrawColor(...colors.border);
    doc.roundedRect(22, startY, pageWidth - 44, yPos - startY, 2, 2, 'S');
    yPos += 5;
  });
  
  addPDFFooter(doc);
  doc.save('symptoms-journal.pdf');
};

// Medications Export
export const exportMedications = async (medications: Medication[]) => {
  if (medications.length === 0) {
    alert('No medications to export');
    return;
  }

  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const current = medications.filter(m => m.stillTaking);
  const past = medications.filter(m => !m.stillTaking);
  
  let yPos = addPDFHeader(doc, {
    title: 'Medication History',
    subtitle: 'Prescription Documentation for VA Claims'
  });
  
  yPos = drawSummaryBox(doc, [
    { value: medications.length, label: 'Total Medications' },
    { value: current.length, label: 'Currently Taking' },
    { value: past.length, label: 'Discontinued' },
    { value: medications.filter(m => m.sideEffects).length, label: 'With Side Effects' }
  ], yPos);
  
  yPos = drawInfoBox(doc, 'Documentation Tip: Medication history demonstrates ongoing treatment for your conditions and can support the severity of your disabilities.', yPos);
  
  // Current medications table
  if (current.length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(...colors.secondary);
    doc.setFont('helvetica', 'bold');
    doc.text(`Current Medications (${current.length})`, 20, yPos);
    yPos += 8;
    
    // Table header
    doc.setFillColor(...colors.background);
    doc.rect(20, yPos - 4, pageWidth - 40, 8, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...colors.secondary);
    doc.text('Medication', 25, yPos);
    doc.text('Prescribed For', 70, yPos);
    doc.text('Start Date', 120, yPos);
    doc.text('Side Effects', 150, yPos);
    yPos += 8;
    
    doc.setFont('helvetica', 'normal');
    current.forEach(med => {
      yPos = checkPageBreak(doc, yPos, 10);
      doc.setTextColor(...colors.secondary);
      doc.text(med.name?.substring(0, 25) || '', 25, yPos);
      doc.text(med.prescribedFor?.substring(0, 25) || 'N/A', 70, yPos);
      doc.text(new Date(med.startDate).toLocaleDateString(), 120, yPos);
      doc.text(med.sideEffects?.substring(0, 20) || 'None', 150, yPos);
      yPos += 6;
    });
    yPos += 5;
  }
  
  // Past medications table
  if (past.length > 0) {
    yPos = checkPageBreak(doc, yPos, 30);
    
    doc.setFontSize(12);
    doc.setTextColor(...colors.secondary);
    doc.setFont('helvetica', 'bold');
    doc.text(`Past Medications (${past.length})`, 20, yPos);
    yPos += 8;
    
    doc.setFillColor(...colors.background);
    doc.rect(20, yPos - 4, pageWidth - 40, 8, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...colors.secondary);
    doc.text('Medication', 25, yPos);
    doc.text('Prescribed For', 65, yPos);
    doc.text('Duration', 110, yPos);
    doc.text('Side Effects', 155, yPos);
    yPos += 8;
    
    doc.setFont('helvetica', 'normal');
    past.forEach(med => {
      yPos = checkPageBreak(doc, yPos, 10);
      doc.setTextColor(...colors.secondary);
      doc.text(med.name?.substring(0, 22) || '', 25, yPos);
      doc.text(med.prescribedFor?.substring(0, 22) || 'N/A', 65, yPos);
      const duration = `${new Date(med.startDate).toLocaleDateString()} - ${med.endDate ? new Date(med.endDate).toLocaleDateString() : 'N/A'}`;
      doc.text(duration.substring(0, 22), 110, yPos);
      doc.text(med.sideEffects?.substring(0, 15) || 'None', 155, yPos);
      yPos += 6;
    });
  }
  
  addPDFFooter(doc);
  doc.save('medications.pdf');
};

// Exposures Export
export const exportExposures = async (exposures: Exposure[]) => {
  if (exposures.length === 0) {
    alert('No exposures to export');
    return;
  }

  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const sorted = [...exposures].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  const noPPE = exposures.filter(e => !e.ppeProvided).length;
  
  let yPos = addPDFHeader(doc, {
    title: 'Hazardous Exposure Log',
    subtitle: 'PACT Act & Toxic Exposure Documentation'
  });
  
  yPos = drawInfoBox(doc, 'PACT Act Information: The PACT Act (2022) expanded VA healthcare and benefits for veterans exposed to burn pits, Agent Orange, and other toxic substances. If you served in qualifying locations and have related conditions, you may be eligible for presumptive benefits.', yPos, 'success');
  
  yPos = drawSummaryBox(doc, [
    { value: exposures.length, label: 'Total Exposures' },
    { value: noPPE, label: 'Without PPE' },
    { value: exposures.filter(e => e.ppeProvided).length, label: 'With PPE' }
  ], yPos);
  
  doc.setFontSize(14);
  doc.setTextColor(...colors.secondary);
  doc.setFont('helvetica', 'bold');
  doc.text(`Hazardous Exposure Log (${exposures.length} entries)`, 20, yPos);
  yPos += 10;
  
  sorted.forEach((exposure) => {
    yPos = checkPageBreak(doc, yPos, 45);
    
    const startY = yPos;
    const hasPPE = exposure.ppeProvided;
    
    // Left border indicator
    doc.setFillColor(...(hasPPE ? colors.success : colors.danger));
    doc.rect(20, startY, 2, 35, 'F');
    
    yPos += 5;
    
    // Header
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.secondary);
    doc.text(new Date(exposure.date).toLocaleDateString(), 25, yPos);
    
    // PPE badge
    doc.setFillColor(...(hasPPE ? colors.successBg : colors.dangerBg));
    doc.roundedRect(100, yPos - 4, 25, 6, 1, 1, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...(hasPPE ? colors.success : colors.danger));
    doc.text(hasPPE ? 'PPE Provided' : 'No PPE', 112.5, yPos, { align: 'center' });
    yPos += 7;
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    
    doc.setTextColor(...colors.muted);
    doc.text('Exposure Type:', 25, yPos);
    doc.setTextColor(...colors.secondary);
    doc.setFont('helvetica', 'bold');
    doc.text(exposure.type || 'N/A', 60, yPos);
    doc.setFont('helvetica', 'normal');
    yPos += 5;
    
    const fields = [
      { label: 'Location', value: exposure.location },
      { label: 'Duration', value: exposure.duration },
      { label: 'Details', value: exposure.details },
      { label: 'Witnesses', value: exposure.witnesses },
    ];
    
    fields.forEach(field => {
      if (field.value) {
        doc.setTextColor(...colors.muted);
        doc.text(`${field.label}:`, 25, yPos);
        const lines = wrapText(doc, field.value, pageWidth - 70);
        doc.setTextColor(...colors.secondary);
        doc.text(lines, 55, yPos);
        yPos += lines.length * 4 + 2;
      }
    });
    
    yPos += 3;
    doc.setDrawColor(...colors.border);
    doc.roundedRect(22, startY, pageWidth - 44, yPos - startY, 2, 2, 'S');
    yPos += 5;
  });
  
  addPDFFooter(doc);
  doc.save('exposures.pdf');
};

// Documents Checklist Export
export const exportDocuments = async (documents: DocumentItem[]) => {
  if (documents.length === 0) {
    alert('No documents to export');
    return;
  }

  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const completed = documents.filter(d => d.status === 'Obtained' || d.status === 'Submitted');
  const inProgress = documents.filter(d => d.status === 'In Progress');
  const notStarted = documents.filter(d => d.status === 'Not Started');
  
  let yPos = addPDFHeader(doc, {
    title: 'Documents Checklist',
    subtitle: 'VA Claims Documentation Status'
  });
  
  yPos = drawSummaryBox(doc, [
    { value: documents.length, label: 'Total Documents' },
    { value: completed.length, label: 'Completed' },
    { value: inProgress.length, label: 'In Progress' },
    { value: notStarted.length, label: 'Not Started' }
  ], yPos);
  
  yPos = drawInfoBox(doc, 'Documentation Checklist: Having all required documents organized and ready will help expedite your VA claims process. Keep multiple copies of critical documents.', yPos);
  
  doc.setFontSize(12);
  doc.setTextColor(...colors.secondary);
  doc.setFont('helvetica', 'bold');
  doc.text('Documents Checklist', 20, yPos);
  yPos += 8;
  
  // Table header
  doc.setFillColor(...colors.background);
  doc.rect(20, yPos - 4, pageWidth - 40, 8, 'F');
  doc.setFontSize(8);
  doc.text('Document', 25, yPos);
  doc.text('Status', 100, yPos);
  doc.text('Copies', 130, yPos);
  doc.text('Notes', 150, yPos);
  yPos += 8;
  
  doc.setFont('helvetica', 'normal');
  documents.forEach(docItem => {
    yPos = checkPageBreak(doc, yPos, 10);
    
    doc.setTextColor(...colors.secondary);
    doc.text(docItem.name?.substring(0, 40) || '', 25, yPos);
    
    // Status badge
    const status = docItem.status || 'Not Started';
    const statusColor = status === 'Submitted' || status === 'Obtained' ? colors.successBg 
      : status === 'In Progress' ? colors.warningBg : colors.background;
    const statusTextColor = status === 'Submitted' || status === 'Obtained' ? colors.success 
      : status === 'In Progress' ? colors.warning : colors.muted;
    
    doc.setFillColor(...statusColor);
    doc.roundedRect(98, yPos - 3, 25, 5, 1, 1, 'F');
    doc.setFontSize(7);
    doc.setTextColor(...statusTextColor);
    doc.text(status, 110.5, yPos, { align: 'center' });
    
    doc.setFontSize(8);
    doc.setTextColor(...colors.secondary);
    doc.text(String(docItem.count || 0), 135, yPos);
    doc.text(docItem.notes?.substring(0, 25) || '', 150, yPos);
    yPos += 7;
  });
  
  addPDFFooter(doc);
  doc.save('documents-checklist.pdf');
};

// Buddy Contacts Export
export const exportBuddyContacts = async (contacts: BuddyContact[]) => {
  if (contacts.length === 0) {
    alert('No buddy contacts to export');
    return;
  }

  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const received = contacts.filter(c => c.statementStatus === 'Received' || c.statementStatus === 'Submitted');
  const requested = contacts.filter(c => c.statementStatus === 'Requested');
  const notRequested = contacts.filter(c => c.statementStatus === 'Not Requested');
  
  let yPos = addPDFHeader(doc, {
    title: 'Buddy Contacts List',
    subtitle: 'Witness Statement Contacts for VA Claims'
  });
  
  yPos = drawSummaryBox(doc, [
    { value: contacts.length, label: 'Total Contacts' },
    { value: received.length, label: 'Statements Received' },
    { value: requested.length, label: 'Pending Request' },
    { value: notRequested.length, label: 'Not Requested' }
  ], yPos);
  
  yPos = drawInfoBox(doc, 'Buddy Statements (VA Form 21-10210): Lay/witness statements from fellow service members can provide critical evidence for your VA claim by corroborating your account of in-service events, injuries, and symptoms.', yPos);
  
  doc.setFontSize(14);
  doc.setTextColor(...colors.secondary);
  doc.setFont('helvetica', 'bold');
  doc.text('Buddy Contacts for Witness Statements', 20, yPos);
  yPos += 10;
  
  contacts.forEach((contact) => {
    yPos = checkPageBreak(doc, yPos, 45);
    
    const startY = yPos;
    yPos += 5;
    
    // Name and rank
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.secondary);
    const name = `${contact.rank ? `${contact.rank} ` : ''}${contact.name}`;
    doc.text(name, 25, yPos);
    
    // Status badge
    const status = contact.statementStatus || 'Not Requested';
    const statusColor = status === 'Submitted' || status === 'Received' ? colors.successBg 
      : status === 'Requested' ? colors.warningBg : colors.background;
    const statusTextColor = status === 'Submitted' || status === 'Received' ? colors.success 
      : status === 'Requested' ? colors.warning : colors.muted;
    
    doc.setFillColor(...statusColor);
    doc.roundedRect(120, yPos - 4, 30, 6, 1, 1, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...statusTextColor);
    doc.text(status, 135, yPos, { align: 'center' });
    yPos += 7;
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    
    if (contact.relationship) {
      doc.setTextColor(...colors.muted);
      doc.text('Relationship:', 25, yPos);
      doc.setTextColor(...colors.secondary);
      doc.text(contact.relationship, 60, yPos);
      yPos += 5;
    }
    
    if (contact.whatTheyWitnessed) {
      doc.setFillColor(...colors.background);
      const witnessLines = wrapText(doc, contact.whatTheyWitnessed, pageWidth - 60);
      const boxHeight = witnessLines.length * 4 + 8;
      doc.roundedRect(25, yPos - 2, pageWidth - 50, boxHeight, 1, 1, 'F');
      
      doc.setTextColor(...colors.muted);
      doc.setFont('helvetica', 'bold');
      doc.text('Can Verify:', 28, yPos + 4);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...colors.secondary);
      doc.text(witnessLines, 28, yPos + 10);
      yPos += boxHeight + 3;
    }
    
    if (contact.contactInfo) {
      doc.setTextColor(...colors.muted);
      doc.text('Contact:', 25, yPos);
      doc.setTextColor(...colors.secondary);
      doc.text(contact.contactInfo, 50, yPos);
      yPos += 5;
    }
    
    yPos += 3;
    doc.setDrawColor(...colors.border);
    doc.roundedRect(22, startY, pageWidth - 44, yPos - startY, 2, 2, 'S');
    yPos += 5;
  });
  
  addPDFFooter(doc);
  doc.save('buddy-contacts.pdf');
};

// Comprehensive Evidence Export
export const exportAllEvidence = async (data: ClaimsData) => {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();

  let yPos = addPDFHeader(doc, {
    title: 'Complete VA Evidence Package',
    subtitle: 'Comprehensive Documentation for VA Disability Claims'
  });
  
  // Summary counts
  const counts = {
    conditions: data.claimConditions?.length || 0,
    medicalVisits: data.medicalVisits?.length || 0,
    symptoms: data.symptoms?.length || 0,
    medications: data.medications?.length || 0,
    exposures: data.exposures?.length || 0,
    buddyContacts: data.buddyContacts?.length || 0,
    documents: data.documents?.length || 0,
  };
  
  yPos = drawSummaryBox(doc, [
    { value: counts.conditions, label: 'Conditions' },
    { value: counts.medicalVisits, label: 'Medical Visits' },
    { value: counts.symptoms, label: 'Symptoms' },
    { value: counts.medications, label: 'Medications' }
  ], yPos);
  
  yPos = drawSummaryBox(doc, [
    { value: counts.exposures, label: 'Exposures' },
    { value: counts.buddyContacts, label: 'Buddy Contacts' },
    { value: counts.documents, label: 'Documents' }
  ], yPos);
  
  yPos = drawInfoBox(doc, 'This document provides a comprehensive summary of all evidence collected for your VA disability claim. Use this as a reference when meeting with your VSO or preparing for C&P exams.', yPos);
  
  // Conditions being claimed
  if (data.claimConditions && data.claimConditions.length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(...colors.secondary);
    doc.setFont('helvetica', 'bold');
    doc.text('Conditions Being Claimed', 20, yPos);
    yPos += 8;
    
    data.claimConditions.forEach((condition: ClaimCondition) => {
      yPos = checkPageBreak(doc, yPos, 15);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(`• ${condition.name}`, 25, yPos);
      
      if (condition.claimType) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(...colors.muted);
        doc.text(` (${condition.claimType})`, 25 + doc.getTextWidth(`• ${condition.name}`) + 2, yPos);
      }
      yPos += 6;
    });
    yPos += 5;
  }
  
  // Service info
  if (data.veteranInfo) {
    yPos = checkPageBreak(doc, yPos, 30);
    doc.setFontSize(12);
    doc.setTextColor(...colors.secondary);
    doc.setFont('helvetica', 'bold');
    doc.text('Veteran Information', 20, yPos);
    yPos += 8;
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    
    if (data.veteranInfo.separationDate) {
      doc.setTextColor(...colors.muted);
      doc.text('Separation Date:', 25, yPos);
      doc.setTextColor(...colors.secondary);
      doc.text(data.veteranInfo.separationDate, 70, yPos);
      yPos += 5;
    }
    
    if (data.veteranInfo.branch) {
      doc.setTextColor(...colors.muted);
      doc.text('Branch:', 25, yPos);
      doc.setTextColor(...colors.secondary);
      doc.text(data.veteranInfo.branch, 70, yPos);
      yPos += 5;
    }
  }
  
  addPDFFooter(doc);
  doc.save('complete-evidence-package.pdf');
};

// Migraines Export
export const exportMigraines = async (migraines: MigraineEntry[], stats?: { totalLast30Days: number; prostratingLast30Days: number; totalAll: number }) => {
  if (migraines.length === 0) {
    alert('No migraine entries to export');
    return;
  }

  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const sorted = [...migraines].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  
  // Calculate stats if not provided
  const last30Days = migraines.filter(m => {
    const date = new Date(m.date);
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
    return date >= thirtyDaysAgo;
  });
  
  const calculatedStats = stats || {
    totalLast30Days: last30Days.length,
    prostratingLast30Days: last30Days.filter(m => m.severity === 'Prostrating').length,
    totalAll: migraines.length,
  };
  
  let yPos = addPDFHeader(doc, {
    title: 'Migraine Log - VA Disability Evidence',
    subtitle: 'Headache Documentation for VA Claims'
  });
  
  yPos = drawSummaryBox(doc, [
    { value: calculatedStats.totalLast30Days, label: 'Attacks (30 Days)' },
    { value: calculatedStats.prostratingLast30Days, label: 'Prostrating (30 Days)' },
    { value: calculatedStats.totalAll, label: 'Total Logged' }
  ], yPos);
  
  yPos = drawInfoBox(doc, 'VA Rating Information: Migraines are rated under 38 CFR § 4.124a, Diagnostic Code 8100. The VA considers the frequency of "prostrating" attacks (requiring bed rest) when determining ratings. 10% = 1 in 2 months | 30% = once a month | 50% = very frequent with severe economic impact.', yPos);
  
  doc.setFontSize(14);
  doc.setTextColor(...colors.secondary);
  doc.setFont('helvetica', 'bold');
  doc.text(`Detailed Migraine Log (${migraines.length} entries)`, 20, yPos);
  yPos += 10;
  
  sorted.forEach((migraine) => {
    yPos = checkPageBreak(doc, yPos, 50);
    
    const startY = yPos;
    yPos += 5;
    
    // Header
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.secondary);
    doc.text(`${new Date(migraine.date).toLocaleDateString()} at ${migraine.time || 'N/A'}`, 25, yPos);
    
    // Severity badge
    const severity = migraine.severity || 'Moderate';
    const severityColor = severity === 'Prostrating' ? colors.dangerBg 
      : severity === 'Severe' ? [254, 215, 170] as [number, number, number]
      : severity === 'Moderate' ? colors.warningBg : colors.successBg;
    const severityTextColor = severity === 'Prostrating' ? colors.danger 
      : severity === 'Severe' ? [156, 66, 33] as [number, number, number]
      : severity === 'Moderate' ? colors.warning : colors.success;
    
    doc.setFillColor(...severityColor);
    doc.roundedRect(120, yPos - 4, 30, 6, 1, 1, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...severityTextColor);
    doc.text(severity, 135, yPos, { align: 'center' });
    yPos += 7;
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    
    // Duration
    doc.setTextColor(...colors.muted);
    doc.text('Duration:', 25, yPos);
    doc.setTextColor(...colors.secondary);
    doc.text(migraineDurations[migraine.duration] || migraine.duration || 'N/A', 55, yPos);
    yPos += 5;
    
    // Impact
    doc.setTextColor(...colors.muted);
    doc.text('Impact:', 25, yPos);
    doc.setTextColor(...colors.secondary);
    doc.text(migraine.impact || 'N/A', 55, yPos);
    yPos += 5;
    
    // Symptoms
    if (migraine.symptoms && migraine.symptoms.length > 0) {
      doc.setTextColor(...colors.muted);
      doc.text('Symptoms:', 25, yPos);
      doc.setTextColor(...colors.secondary);
      const symptomsText = migraine.symptoms.join(', ');
      const symptomLines = wrapText(doc, symptomsText, pageWidth - 70);
      doc.text(symptomLines, 55, yPos);
      yPos += symptomLines.length * 4 + 2;
    }
    
    // Triggers
    if (migraine.triggers && migraine.triggers.length > 0) {
      doc.setTextColor(...colors.muted);
      doc.text('Triggers:', 25, yPos);
      doc.setTextColor(...colors.secondary);
      doc.text(migraine.triggers.join(', '), 55, yPos);
      yPos += 5;
    }
    
    // Treatment
    if (migraine.treatment) {
      doc.setTextColor(...colors.muted);
      doc.text('Treatment:', 25, yPos);
      const treatmentLines = wrapText(doc, migraine.treatment, pageWidth - 70);
      doc.setTextColor(...colors.secondary);
      doc.text(treatmentLines, 55, yPos);
      yPos += treatmentLines.length * 4 + 2;
    }
    
    // Notes
    if (migraine.notes) {
      doc.setTextColor(...colors.muted);
      doc.text('Notes:', 25, yPos);
      const noteLines = wrapText(doc, migraine.notes, pageWidth - 70);
      doc.setTextColor(...colors.secondary);
      doc.text(noteLines, 55, yPos);
      yPos += noteLines.length * 4 + 2;
    }
    
    yPos += 3;
    doc.setDrawColor(...colors.border);
    doc.roundedRect(22, startY, pageWidth - 44, yPos - startY, 2, 2, 'S');
    yPos += 5;
  });
  
  addPDFFooter(doc);
  doc.save('migraine-log.pdf');
};

// Condition-Specific Evidence Package Export
export const exportConditionEvidence = async (
  conditionName: string,
  claimDate: string,
  evidenceScore: number,
  linkedSymptoms: SymptomEntry[],
  linkedMedicalVisits: MedicalVisit[],
  linkedMedications: Medication[],
  linkedExposures: Exposure[],
  linkedBuddyContacts: BuddyContact[]
) => {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  let yPos = addPDFHeader(doc, {
    title: `Evidence Package: ${conditionName}`,
    subtitle: 'Condition-Specific Evidence Summary for VA Claims'
  });
  
  // Claim info box
  doc.setFillColor(...colors.background);
  doc.roundedRect(20, yPos, pageWidth - 40, 25, 2, 2, 'F');
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.secondary);
  doc.text('Condition:', 25, yPos + 8);
  doc.setFont('helvetica', 'normal');
  doc.text(conditionName, 55, yPos + 8);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Claim Started:', 25, yPos + 16);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date(claimDate).toLocaleDateString(), 55, yPos + 16);
  
  // Evidence strength badge
  const strengthColor = evidenceScore >= 75 ? colors.success : evidenceScore >= 50 ? colors.warning : colors.danger;
  const strengthBg = evidenceScore >= 75 ? colors.successBg : evidenceScore >= 50 ? colors.warningBg : colors.dangerBg;
  const strengthLabel = evidenceScore >= 75 ? 'Strong' : evidenceScore >= 50 ? 'Building' : 'Needs Work';
  
  doc.setFillColor(...strengthBg);
  doc.roundedRect(130, yPos + 5, 50, 15, 2, 2, 'F');
  doc.setFontSize(12);
  doc.setTextColor(...strengthColor);
  doc.setFont('helvetica', 'bold');
  doc.text(`${strengthLabel} (${evidenceScore}%)`, 155, yPos + 14, { align: 'center' });
  
  yPos += 35;
  
  // Summary box
  yPos = drawSummaryBox(doc, [
    { value: linkedSymptoms.length, label: 'Symptoms' },
    { value: linkedMedicalVisits.length, label: 'Medical Visits' },
    { value: linkedMedications.length, label: 'Medications' },
    { value: linkedExposures.length, label: 'Exposures' }
  ], yPos);
  
  // Educational disclaimer
  yPos = drawInfoBox(doc, 'EDUCATIONAL PURPOSES ONLY: This evidence package is for personal organization and VSO consultation. It is not an official VA document. Always consult with an accredited VSO or VA representative before filing claims.', yPos);
  
  // Symptoms Section
  if (linkedSymptoms.length > 0) {
    yPos = checkPageBreak(doc, yPos, 30);
    doc.setFontSize(14);
    doc.setTextColor(...colors.secondary);
    doc.setFont('helvetica', 'bold');
    doc.text(`Symptoms Documentation (${linkedSymptoms.length})`, 20, yPos);
    yPos += 10;
    
    linkedSymptoms.forEach((symptom) => {
      yPos = checkPageBreak(doc, yPos, 30);
      
      const startY = yPos;
      yPos += 5;
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...colors.secondary);
      doc.text(new Date(symptom.date).toLocaleDateString(), 25, yPos);
      
      // Severity badge
      const severity = symptom.severity || 0;
      const sevColor = severity <= 3 ? colors.successBg : severity <= 6 ? colors.warningBg : colors.dangerBg;
      const sevText = severity <= 3 ? colors.success : severity <= 6 ? colors.warning : colors.danger;
      doc.setFillColor(...sevColor);
      doc.roundedRect(100, yPos - 4, 20, 6, 1, 1, 'F');
      doc.setFontSize(8);
      doc.setTextColor(...sevText);
      doc.text(`${severity}/10`, 110, yPos, { align: 'center' });
      yPos += 7;
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      
      if (symptom.symptom) {
        doc.setTextColor(...colors.muted);
        doc.text('Symptom:', 25, yPos);
        doc.setTextColor(...colors.secondary);
        doc.text(symptom.symptom, 55, yPos);
        yPos += 5;
      }
      
      if (symptom.bodyArea) {
        doc.setTextColor(...colors.muted);
        doc.text('Body Area:', 25, yPos);
        doc.setTextColor(...colors.secondary);
        doc.text(symptom.bodyArea, 55, yPos);
        yPos += 5;
      }
      
      if (symptom.frequency) {
        doc.setTextColor(...colors.muted);
        doc.text('Frequency:', 25, yPos);
        doc.setTextColor(...colors.secondary);
        doc.text(symptom.frequency, 55, yPos);
        yPos += 5;
      }
      
      if (symptom.dailyImpact) {
        doc.setTextColor(...colors.muted);
        doc.text('Daily Impact:', 25, yPos);
        const impactLines = wrapText(doc, symptom.dailyImpact, pageWidth - 70);
        doc.setTextColor(...colors.secondary);
        doc.text(impactLines, 55, yPos);
        yPos += impactLines.length * 4 + 2;
      }
      
      yPos += 3;
      doc.setDrawColor(...colors.border);
      doc.roundedRect(22, startY, pageWidth - 44, yPos - startY, 2, 2, 'S');
      yPos += 5;
    });
  }
  
  // Medical Visits Section
  if (linkedMedicalVisits.length > 0) {
    yPos = checkPageBreak(doc, yPos, 30);
    doc.setFontSize(14);
    doc.setTextColor(...colors.secondary);
    doc.setFont('helvetica', 'bold');
    doc.text(`Medical Visits (${linkedMedicalVisits.length})`, 20, yPos);
    yPos += 10;
    
    linkedMedicalVisits.forEach((visit) => {
      yPos = checkPageBreak(doc, yPos, 35);
      
      const startY = yPos;
      yPos += 5;
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...colors.secondary);
      doc.text(new Date(visit.date).toLocaleDateString(), 25, yPos);
      
      doc.setFillColor(...colors.infoBg);
      doc.roundedRect(100, yPos - 4, 40, 6, 1, 1, 'F');
      doc.setFontSize(8);
      doc.setTextColor(...colors.primary);
      doc.text(visit.visitType || 'Visit', 120, yPos, { align: 'center' });
      yPos += 7;
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      
      const visitFields = [
        { label: 'Reason', value: visit.reason },
        { label: 'Location', value: visit.location },
        { label: 'Provider', value: visit.provider },
        { label: 'Diagnosis', value: visit.diagnosis },
        { label: 'Treatment', value: visit.treatment },
      ];
      
      visitFields.forEach(field => {
        if (field.value) {
          doc.setTextColor(...colors.muted);
          doc.text(`${field.label}:`, 25, yPos);
          const lines = wrapText(doc, field.value, pageWidth - 70);
          doc.setTextColor(...colors.secondary);
          doc.text(lines, 55, yPos);
          yPos += lines.length * 4 + 2;
        }
      });
      
      yPos += 3;
      doc.setDrawColor(...colors.border);
      doc.roundedRect(22, startY, pageWidth - 44, yPos - startY, 2, 2, 'S');
      yPos += 5;
    });
  }
  
  // Medications Section
  if (linkedMedications.length > 0) {
    yPos = checkPageBreak(doc, yPos, 30);
    doc.setFontSize(14);
    doc.setTextColor(...colors.secondary);
    doc.setFont('helvetica', 'bold');
    doc.text(`Medications (${linkedMedications.length})`, 20, yPos);
    yPos += 8;
    
    // Table header
    doc.setFillColor(...colors.background);
    doc.rect(20, yPos - 4, pageWidth - 40, 8, 'F');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.secondary);
    doc.text('Medication', 25, yPos);
    doc.text('Prescribed For', 70, yPos);
    doc.text('Start Date', 120, yPos);
    doc.text('Status', 155, yPos);
    yPos += 8;
    
    doc.setFont('helvetica', 'normal');
    linkedMedications.forEach(med => {
      yPos = checkPageBreak(doc, yPos, 10);
      doc.setTextColor(...colors.secondary);
      doc.text((med.name || '').substring(0, 25), 25, yPos);
      doc.text((med.prescribedFor || 'N/A').substring(0, 25), 70, yPos);
      doc.text(med.startDate ? new Date(med.startDate).toLocaleDateString() : 'N/A', 120, yPos);
      const statusColor = med.stillTaking ? colors.success : colors.muted;
      doc.setTextColor(...statusColor);
      doc.text(med.stillTaking ? 'Current' : 'Discontinued', 155, yPos);
      yPos += 6;
    });
    yPos += 5;
  }
  
  // Exposures Section
  if (linkedExposures.length > 0) {
    yPos = checkPageBreak(doc, yPos, 30);
    doc.setFontSize(14);
    doc.setTextColor(...colors.secondary);
    doc.setFont('helvetica', 'bold');
    doc.text(`Service-Connected Exposures (${linkedExposures.length})`, 20, yPos);
    yPos += 10;
    
    linkedExposures.forEach((exposure) => {
      yPos = checkPageBreak(doc, yPos, 25);
      
      const startY = yPos;
      yPos += 5;
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...colors.secondary);
      doc.text(exposure.type || 'Exposure', 25, yPos);
      
      doc.setFillColor(...colors.warningBg);
      doc.roundedRect(130, yPos - 4, 50, 6, 1, 1, 'F');
      doc.setFontSize(8);
      doc.setTextColor(...colors.warning);
      doc.text(exposure.location || 'N/A', 155, yPos, { align: 'center' });
      yPos += 7;
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      
      if (exposure.date) {
        doc.setTextColor(...colors.muted);
        doc.text('Date:', 25, yPos);
        doc.setTextColor(...colors.secondary);
        doc.text(new Date(exposure.date).toLocaleDateString(), 55, yPos);
        yPos += 5;
      }
      
      if (exposure.duration) {
        doc.setTextColor(...colors.muted);
        doc.text('Duration:', 25, yPos);
        doc.setTextColor(...colors.secondary);
        doc.text(exposure.duration, 55, yPos);
        yPos += 5;
      }
      
      if (exposure.details) {
        doc.setTextColor(...colors.muted);
        doc.text('Details:', 25, yPos);
        const detailLines = wrapText(doc, exposure.details, pageWidth - 70);
        doc.setTextColor(...colors.secondary);
        doc.text(detailLines, 55, yPos);
        yPos += detailLines.length * 4 + 2;
      }
      
      yPos += 3;
      doc.setDrawColor(...colors.border);
      doc.roundedRect(22, startY, pageWidth - 44, yPos - startY, 2, 2, 'S');
      yPos += 5;
    });
  }
  
  // Buddy Statements Section
  if (linkedBuddyContacts.length > 0) {
    yPos = checkPageBreak(doc, yPos, 30);
    doc.setFontSize(14);
    doc.setTextColor(...colors.secondary);
    doc.setFont('helvetica', 'bold');
    doc.text(`Buddy Statements (${linkedBuddyContacts.length})`, 20, yPos);
    yPos += 10;
    
    linkedBuddyContacts.forEach((buddy) => {
      yPos = checkPageBreak(doc, yPos, 25);
      
      const startY = yPos;
      yPos += 5;
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...colors.secondary);
      doc.text(`${buddy.name} (${buddy.rank || 'N/A'})`, 25, yPos);
      yPos += 7;
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      
      if (buddy.relationship) {
        doc.setTextColor(...colors.muted);
        doc.text('Relationship:', 25, yPos);
        doc.setTextColor(...colors.secondary);
        doc.text(buddy.relationship, 55, yPos);
        yPos += 5;
      }
      
      if (buddy.whatTheyWitnessed) {
        doc.setTextColor(...colors.muted);
        doc.text('Witnessed:', 25, yPos);
        const witnessLines = wrapText(doc, buddy.whatTheyWitnessed, pageWidth - 70);
        doc.setTextColor(...colors.secondary);
        doc.text(witnessLines, 55, yPos);
        yPos += witnessLines.length * 4 + 2;
      }
      
      if (buddy.statementStatus) {
        doc.setTextColor(...colors.muted);
        doc.text('Status:', 25, yPos);
        const statusColor = buddy.statementStatus === 'Received' || buddy.statementStatus === 'Submitted' 
          ? colors.success : colors.warning;
        doc.setTextColor(...statusColor);
        doc.text(buddy.statementStatus, 55, yPos);
        yPos += 5;
      }
      
      yPos += 3;
      doc.setDrawColor(...colors.border);
      doc.roundedRect(22, startY, pageWidth - 44, yPos - startY, 2, 2, 'S');
      yPos += 5;
    });
  }
  
  // Final disclaimer box
  yPos = checkPageBreak(doc, yPos, 30);
  doc.setFillColor(...colors.warningBg);
  doc.roundedRect(20, yPos, pageWidth - 40, 20, 2, 2, 'F');
  doc.setFillColor(...colors.warning);
  doc.rect(20, yPos, 3, 20, 'F');
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.warning);
  doc.text('IMPORTANT NOTICE', 28, yPos + 6);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...colors.secondary);
  const notice = 'This evidence package is for educational and organizational purposes only. It is NOT an official VA document. Consult with an accredited VSO before filing any claims.';
  const noticeLines = wrapText(doc, notice, pageWidth - 50);
  doc.text(noticeLines, 28, yPos + 12);
  
  addPDFFooter(doc);
  doc.save(`${conditionName.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()}-evidence-package.pdf`);
};

// Sleep Log Export
export const exportSleepLog = async (entries: SleepEntry[]) => {
  if (entries.length === 0) {
    alert('No sleep entries to export');
    return;
  }

  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const sorted = [...entries].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  // Calculate stats
  const last30Days = entries.filter(e => {
    const date = new Date(e.date);
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
    return date >= thirtyDaysAgo;
  });

  const avgHours = last30Days.length > 0
    ? (last30Days.reduce((sum, e) => sum + e.hoursSlept, 0) / last30Days.length).toFixed(1)
    : '0';
  const cpapNights = last30Days.filter(e => e.usesCPAP);
  const cpapUsed = cpapNights.filter(e => e.cpapUsedLastNight).length;
  const cpapCompliance = cpapNights.length > 0 ? Math.round((cpapUsed / cpapNights.length) * 100) : null;
  const nightmaresCount = last30Days.filter(e => e.nightmares).length;

  let yPos = addPDFHeader(doc, {
    title: 'Sleep Log - VA Disability Evidence',
    subtitle: 'Sleep Apnea Documentation for VA Claims'
  });

  const summaryItems = [
    { value: `${avgHours}h`, label: 'Avg Sleep (30d)' },
    { value: cpapCompliance !== null ? `${cpapCompliance}%` : 'N/A', label: 'CPAP Compliance' },
    { value: nightmaresCount, label: 'Nightmares (30d)' },
    { value: entries.length, label: 'Total Entries' }
  ];

  yPos = drawSummaryBox(doc, summaryItems, yPos);

  yPos = drawInfoBox(doc, 'VA Rating Information: Sleep Apnea is rated under 38 CFR § 4.97, DC 6847. 0% = Asymptomatic with documented disorder | 30% = Persistent daytime hypersomnolence | 50% = Requires breathing assistance device (CPAP) | 100% = Chronic respiratory failure with CO₂ retention or cor pulmonale.', yPos);

  doc.setFontSize(14);
  doc.setTextColor(...colors.secondary);
  doc.setFont('helvetica', 'bold');
  doc.text(`Detailed Sleep Log (${entries.length} entries)`, 20, yPos);
  yPos += 10;

  sorted.forEach((entry) => {
    yPos = checkPageBreak(doc, yPos, 50);

    const startY = yPos;
    yPos += 5;

    // Header
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.secondary);
    doc.text(new Date(entry.date).toLocaleDateString(), 25, yPos);

    // Quality badge
    const quality = entry.quality || 'Fair';
    const qualityColor = quality === 'Excellent' || quality === 'Good' ? colors.successBg
      : quality === 'Fair' ? colors.warningBg : colors.dangerBg;
    const qualityTextColor = quality === 'Excellent' || quality === 'Good' ? colors.success
      : quality === 'Fair' ? colors.warning : colors.danger;

    doc.setFillColor(...qualityColor);
    doc.roundedRect(100, yPos - 4, 25, 6, 1, 1, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...qualityTextColor);
    doc.text(quality, 112.5, yPos, { align: 'center' });

    // Hours badge
    doc.setFillColor(...colors.infoBg);
    doc.roundedRect(130, yPos - 4, 20, 6, 1, 1, 'F');
    doc.setTextColor(...colors.primary);
    doc.text(`${entry.hoursSlept}h`, 140, yPos, { align: 'center' });
    yPos += 7;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');

    // CPAP Info
    if (entry.usesCPAP) {
      doc.setTextColor(...colors.muted);
      doc.text('CPAP:', 25, yPos);
      const cpapText = entry.cpapUsedLastNight
        ? `Used${entry.cpapHoursUsed ? ` (${entry.cpapHoursUsed}h)` : ''}`
        : 'Not Used';
      doc.setTextColor(...(entry.cpapUsedLastNight ? colors.success : colors.danger));
      doc.text(cpapText, 50, yPos);
      yPos += 5;
    }

    // Interruptions
    if (entry.interruptions > 0) {
      doc.setTextColor(...colors.muted);
      doc.text('Interruptions:', 25, yPos);
      doc.setTextColor(...colors.secondary);
      doc.text(String(entry.interruptions), 60, yPos);
      yPos += 5;
    }

    // Daytime Sleepiness
    if (entry.daytimeSleepiness && entry.daytimeSleepiness !== 'None') {
      doc.setTextColor(...colors.muted);
      doc.text('Daytime Sleepiness:', 25, yPos);
      const sleepinessColor = entry.daytimeSleepiness === 'Severe' || entry.daytimeSleepiness === 'Persistent hypersomnolence'
        ? colors.danger : colors.secondary;
      doc.setTextColor(...sleepinessColor);
      doc.text(entry.daytimeSleepiness, 70, yPos);
      yPos += 5;
    }

    // Gasping episodes
    if (entry.timesWokeGasping > 0) {
      doc.setTextColor(...colors.muted);
      doc.text('Woke Gasping:', 25, yPos);
      doc.setTextColor(...colors.danger);
      doc.text(`${entry.timesWokeGasping} times`, 60, yPos);
      yPos += 5;
    }

    // Nightmares (PTSD related)
    if (entry.nightmares) {
      doc.setFillColor(...colors.dangerBg);
      doc.roundedRect(25, yPos - 2, 30, 6, 1, 1, 'F');
      doc.setFontSize(7);
      doc.setTextColor(...colors.danger);
      doc.text('NIGHTMARES', 40, yPos + 2, { align: 'center' });
      doc.setFontSize(9);
      yPos += 8;
    }

    // Impact on work
    if (entry.impactOnWork) {
      doc.setTextColor(...colors.muted);
      doc.text('Impact:', 25, yPos);
      const impactLines = wrapText(doc, entry.impactOnWork, pageWidth - 65);
      doc.setTextColor(...colors.secondary);
      doc.text(impactLines, 50, yPos);
      yPos += impactLines.length * 4 + 2;
    }

    // Notes
    if (entry.notes) {
      doc.setTextColor(...colors.muted);
      doc.text('Notes:', 25, yPos);
      const noteLines = wrapText(doc, entry.notes, pageWidth - 65);
      doc.setTextColor(...colors.secondary);
      doc.text(noteLines, 50, yPos);
      yPos += noteLines.length * 4 + 2;
    }

    yPos += 3;
    doc.setDrawColor(...colors.border);
    doc.roundedRect(22, startY, pageWidth - 44, yPos - startY, 2, 2, 'S');
    yPos += 5;
  });

  addPDFFooter(doc);
  doc.save('sleep-log.pdf');
};

// Buddy Statement Export (Generated Statement)
export const exportBuddyStatement = async (statementText: string, witnessName: string) => {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addPDFHeader(doc, {
    title: 'Buddy/Lay Statement',
    subtitle: 'Witness Statement in Support of VA Disability Claim'
  });

  yPos = drawInfoBox(doc, 'This document should be reviewed, printed, signed, and dated by the witness. The signed statement can then be submitted with VA Form 21-10210 (Lay/Witness Statement).', yPos);

  // Statement content
  doc.setFontSize(10);
  doc.setTextColor(...colors.secondary);
  doc.setFont('helvetica', 'normal');

  const lines = doc.splitTextToSize(statementText, pageWidth - 40);

  lines.forEach((line: string) => {
    yPos = checkPageBreak(doc, yPos, 8);
    doc.text(line, 20, yPos);
    yPos += 5;
  });

  // Signature block
  yPos = checkPageBreak(doc, yPos, 40);
  yPos += 10;

  doc.setDrawColor(...colors.border);
  doc.line(20, yPos, 100, yPos);
  yPos += 5;
  doc.setFontSize(9);
  doc.setTextColor(...colors.muted);
  doc.text('Signature', 20, yPos);

  yPos += 15;
  doc.line(20, yPos, 100, yPos);
  yPos += 5;
  doc.text('Printed Name', 20, yPos);

  yPos += 15;
  doc.line(20, yPos, 80, yPos);
  yPos += 5;
  doc.text('Date', 20, yPos);

  addPDFFooter(doc);
  doc.save(`buddy-statement-${witnessName.replace(/\s+/g, '-').toLowerCase() || 'draft'}.pdf`);
};

// Stressor Statement Export (PTSD)
export const exportStressorStatement = async (statementText: string) => {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addPDFHeader(doc, {
    title: 'Stressor Statement',
    subtitle: 'PTSD Stressor Documentation for VA Claims'
  });

  yPos = drawInfoBox(doc, 'This statement documents traumatic events for PTSD claims. Print, sign, and date before submitting. Keep a copy for your records.', yPos);

  doc.setFontSize(10);
  doc.setTextColor(...colors.secondary);
  doc.setFont('helvetica', 'normal');

  const lines = doc.splitTextToSize(statementText, pageWidth - 40);

  lines.forEach((line: string) => {
    yPos = checkPageBreak(doc, yPos, 8);
    doc.text(line, 20, yPos);
    yPos += 5;
  });

  addPDFFooter(doc);
  doc.save('stressor-statement.pdf');
};

// Personal Statement Export
export const exportPersonalStatement = async (statementText: string, conditionName?: string) => {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addPDFHeader(doc, {
    title: 'Personal Statement',
    subtitle: conditionName ? `Statement in Support of Claim: ${conditionName}` : 'Statement in Support of VA Disability Claim'
  });

  yPos = drawInfoBox(doc, 'This personal statement describes how your condition affects daily life. Print, sign, and date before submitting to the VA.', yPos);

  doc.setFontSize(10);
  doc.setTextColor(...colors.secondary);
  doc.setFont('helvetica', 'normal');

  const lines = doc.splitTextToSize(statementText, pageWidth - 40);

  lines.forEach((line: string) => {
    yPos = checkPageBreak(doc, yPos, 8);
    doc.text(line, 20, yPos);
    yPos += 5;
  });

  addPDFFooter(doc);
  doc.save(`personal-statement-${conditionName?.replace(/\s+/g, '-').toLowerCase() || 'claim'}.pdf`);
};

// Nexus Letter Template Export
export const exportNexusLetterTemplate = async (statementText: string, conditionName?: string) => {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addPDFHeader(doc, {
    title: 'Nexus Letter Template',
    subtitle: conditionName ? `Medical Opinion Template: ${conditionName}` : 'Medical Opinion Template for VA Claims'
  });

  yPos = drawInfoBox(doc, 'IMPORTANT: This is a TEMPLATE only. A licensed medical professional must review, customize, and sign this letter on their letterhead for it to be valid for VA claims.', yPos);

  doc.setFontSize(10);
  doc.setTextColor(...colors.secondary);
  doc.setFont('helvetica', 'normal');

  const lines = doc.splitTextToSize(statementText, pageWidth - 40);

  lines.forEach((line: string) => {
    yPos = checkPageBreak(doc, yPos, 8);
    doc.text(line, 20, yPos);
    yPos += 5;
  });

  addPDFFooter(doc);
  doc.save(`nexus-letter-template-${conditionName?.replace(/\s+/g, '-').toLowerCase() || 'condition'}.pdf`);
};

// Claim Strategy Export
export const exportClaimStrategy = async (statementText: string) => {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addPDFHeader(doc, {
    title: 'Claim Strategy Plan',
    subtitle: 'Personalized VA Disability Claim Strategy'
  });

  yPos = drawInfoBox(doc, 'This strategy plan is for personal planning purposes only. Consult with an accredited VSO before filing your claims.', yPos);

  doc.setFontSize(10);
  doc.setTextColor(...colors.secondary);
  doc.setFont('helvetica', 'normal');

  const lines = doc.splitTextToSize(statementText, pageWidth - 40);

  lines.forEach((line: string) => {
    yPos = checkPageBreak(doc, yPos, 8);
    doc.text(line, 20, yPos);
    yPos += 5;
  });

  addPDFFooter(doc);
  doc.save(`claim-strategy-${new Date().toISOString().split('T')[0]}.pdf`);
};

// Buddy Statement Template Export
export const exportBuddyStatementTemplate = async (templateText: string, templateTitle?: string) => {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addPDFHeader(doc, {
    title: 'Buddy Statement Template',
    subtitle: templateTitle || 'Witness Statement Template for VA Claims'
  });

  yPos = drawInfoBox(doc, 'This is a template for buddy/lay statements. The witness should fill in the specific details, print, sign, and date before submission.', yPos);

  doc.setFontSize(10);
  doc.setTextColor(...colors.secondary);
  doc.setFont('helvetica', 'normal');

  const lines = doc.splitTextToSize(templateText, pageWidth - 40);

  lines.forEach((line: string) => {
    yPos = checkPageBreak(doc, yPos, 8);
    doc.text(line, 20, yPos);
    yPos += 5;
  });

  // Signature block
  yPos = checkPageBreak(doc, yPos, 40);
  yPos += 10;

  doc.setDrawColor(...colors.border);
  doc.line(20, yPos, 100, yPos);
  yPos += 5;
  doc.setFontSize(9);
  doc.setTextColor(...colors.muted);
  doc.text('Signature', 20, yPos);

  yPos += 15;
  doc.line(20, yPos, 100, yPos);
  yPos += 5;
  doc.text('Printed Name', 20, yPos);

  yPos += 15;
  doc.line(20, yPos, 80, yPos);
  yPos += 5;
  doc.text('Date', 20, yPos);

  addPDFFooter(doc);
  doc.save(`buddy-statement-template-${templateTitle?.replace(/\s+/g, '-').toLowerCase() || 'general'}.pdf`);
};

// DBQ Prep Sheet Export
export interface DBQPrepSheetData {
  condition: string;
  appointmentType: string;
  appointmentDate: string;
  currentSymptoms: string[];
  customSymptoms: string;
  averagePain: number;
  worstPain: number;
  bestPain: number;
  hasFlareups: boolean;
  flareupFrequency: string;
  flareupDuration: string;
  flareupTriggers: string;
  flareupLimitations: string;
  walkingLimit: string;
  standingLimit: string;
  sittingLimit: string;
  liftingLimit: string;
  sleepImpact: string;
  workImpact: string;
  daysMissed: string;
  currentMedications: string;
  sideEffects: string;
  additionalNotes: string;
}

export const exportDBQPrepSheet = async (data: DBQPrepSheetData) => {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addPDFHeader(doc, {
    title: 'C&P Exam Prep Sheet',
    subtitle: data.condition ? `Condition: ${data.condition}` : 'Disability Benefits Questionnaire Preparation',
  });

  // Appointment info
  doc.setFillColor(...colors.background);
  doc.roundedRect(20, yPos, pageWidth - 40, 22, 2, 2, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.secondary);
  doc.text('Condition:', 25, yPos + 8);
  doc.setFont('helvetica', 'normal');
  doc.text(data.condition || 'Not specified', 55, yPos + 8);
  doc.setFont('helvetica', 'bold');
  doc.text('Appointment:', 25, yPos + 16);
  doc.setFont('helvetica', 'normal');
  const apptType = data.appointmentType.replace('_', ' ').toUpperCase();
  const apptDate = data.appointmentDate ? new Date(data.appointmentDate).toLocaleDateString() : 'Not set';
  doc.text(`${apptType} — ${apptDate}`, 55, yPos + 16);
  yPos += 30;

  // Symptoms section
  yPos = checkPageBreak(doc, yPos, 30);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.secondary);
  doc.text('Symptoms & Pain Levels', 20, yPos);
  yPos += 8;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const allSymptoms = [...data.currentSymptoms, data.customSymptoms].filter(Boolean).join(', ') || 'None specified';
  doc.setTextColor(...colors.muted);
  doc.text('Current Symptoms:', 25, yPos);
  const symptomLines = wrapText(doc, allSymptoms, pageWidth - 75);
  doc.setTextColor(...colors.secondary);
  doc.text(symptomLines, 65, yPos);
  yPos += symptomLines.length * 4 + 4;

  doc.setTextColor(...colors.muted);
  doc.text('Pain Levels:', 25, yPos);
  doc.setTextColor(...colors.secondary);
  doc.text(`Average: ${data.averagePain}/10  |  Worst: ${data.worstPain}/10  |  Best: ${data.bestPain}/10`, 65, yPos);
  yPos += 10;

  // Flare-ups section
  if (data.hasFlareups) {
    yPos = checkPageBreak(doc, yPos, 30);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.secondary);
    doc.text('Flare-ups', 20, yPos);
    yPos += 8;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const flareFields = [
      { label: 'Frequency', value: data.flareupFrequency },
      { label: 'Duration', value: data.flareupDuration },
      { label: 'Triggers', value: data.flareupTriggers },
      { label: 'Limitations', value: data.flareupLimitations },
    ];
    flareFields.forEach(f => {
      if (f.value) {
        doc.setTextColor(...colors.muted);
        doc.text(`${f.label}:`, 25, yPos);
        const lines = wrapText(doc, f.value, pageWidth - 75);
        doc.setTextColor(...colors.secondary);
        doc.text(lines, 65, yPos);
        yPos += lines.length * 4 + 3;
      }
    });
    yPos += 4;
  }

  // Functional impact section
  yPos = checkPageBreak(doc, yPos, 30);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.secondary);
  doc.text('Functional Limitations', 20, yPos);
  yPos += 8;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const funcFields = [
    { label: 'Walking', value: data.walkingLimit },
    { label: 'Standing', value: data.standingLimit },
    { label: 'Sitting', value: data.sittingLimit },
    { label: 'Lifting', value: data.liftingLimit },
    { label: 'Sleep Impact', value: data.sleepImpact },
    { label: 'Work Impact', value: data.workImpact },
    { label: 'Days Missed', value: data.daysMissed },
  ];
  funcFields.forEach(f => {
    if (f.value) {
      yPos = checkPageBreak(doc, yPos, 10);
      doc.setTextColor(...colors.muted);
      doc.text(`${f.label}:`, 25, yPos);
      const lines = wrapText(doc, f.value, pageWidth - 75);
      doc.setTextColor(...colors.secondary);
      doc.text(lines, 65, yPos);
      yPos += lines.length * 4 + 3;
    }
  });
  yPos += 4;

  // Medications section
  yPos = checkPageBreak(doc, yPos, 20);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.secondary);
  doc.text('Medications & Treatments', 20, yPos);
  yPos += 8;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  if (data.currentMedications) {
    doc.setTextColor(...colors.muted);
    doc.text('Current:', 25, yPos);
    const medLines = wrapText(doc, data.currentMedications, pageWidth - 75);
    doc.setTextColor(...colors.secondary);
    doc.text(medLines, 65, yPos);
    yPos += medLines.length * 4 + 3;
  }
  if (data.sideEffects) {
    doc.setTextColor(...colors.muted);
    doc.text('Side Effects:', 25, yPos);
    const seLines = wrapText(doc, data.sideEffects, pageWidth - 75);
    doc.setTextColor(...colors.secondary);
    doc.text(seLines, 65, yPos);
    yPos += seLines.length * 4 + 3;
  }
  yPos += 4;

  // Additional notes
  if (data.additionalNotes) {
    yPos = checkPageBreak(doc, yPos, 20);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.secondary);
    doc.text('Additional Notes', 20, yPos);
    yPos += 8;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...colors.secondary);
    const noteLines = wrapText(doc, data.additionalNotes, pageWidth - 40);
    noteLines.forEach((line: string) => {
      yPos = checkPageBreak(doc, yPos, 8);
      doc.text(line, 25, yPos);
      yPos += 5;
    });
    yPos += 4;
  }

  // Reminders box
  yPos = checkPageBreak(doc, yPos, 35);
  yPos = drawInfoBox(doc, 'REMEMBER: Describe your WORST days, not your best. Be specific about frequency and duration. Mention ALL limitations. Bring copies of relevant medical records.', yPos);

  addPDFFooter(doc);
  doc.save(`dbq-prep-sheet-${data.condition?.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase() || 'general'}.pdf`);
};

// Back Pay Estimate Export
export interface BackPayEstimateData {
  currentRating: number;
  newRating: number;
  effectiveDate: string;
  hasSpouse: boolean;
  dependentCount: number;
  monthlyBefore: number;
  monthlyAfter: number;
  monthlyDifference: number;
  totalBackPay: number;
  months: number;
}

export const exportBackPayEstimate = async (data: BackPayEstimateData) => {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addPDFHeader(doc, {
    title: 'Back Pay Estimate',
    subtitle: 'VA Disability Compensation Estimate',
  });

  yPos = drawInfoBox(doc, 'DISCLAIMER: This is an estimate only. Actual back pay amounts are determined by the VA. Rates shown are approximate. Consult a VSO for precise amounts.', yPos);

  // Summary box
  yPos = drawSummaryBox(doc, [
    { value: `${data.currentRating}%`, label: 'Current Rating' },
    { value: `${data.newRating}%`, label: 'New Rating' },
    { value: String(data.months), label: 'Months Owed' },
  ], yPos);

  // Calculation details
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.secondary);
  doc.text('Calculation Details', 20, yPos);
  yPos += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  const fmt = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 2 }).format(n);

  const rows = [
    { label: 'Effective Date', value: new Date(data.effectiveDate + 'T00:00:00').toLocaleDateString() },
    { label: 'Spouse', value: data.hasSpouse ? 'Yes' : 'No' },
    { label: 'Dependents', value: String(data.dependentCount) },
    { label: `Monthly at ${data.currentRating}%`, value: fmt(data.monthlyBefore) },
    { label: `Monthly at ${data.newRating}%`, value: fmt(data.monthlyAfter) },
    { label: 'Monthly Difference', value: `+${fmt(data.monthlyDifference)}` },
    { label: 'Months of Back Pay', value: String(data.months) },
  ];

  rows.forEach(row => {
    doc.setTextColor(...colors.muted);
    doc.text(row.label + ':', 25, yPos);
    doc.setTextColor(...colors.secondary);
    doc.text(row.value, 85, yPos);
    yPos += 7;
  });

  yPos += 5;

  // Total highlight
  doc.setFillColor(...colors.successBg);
  doc.roundedRect(20, yPos, pageWidth - 40, 25, 2, 2, 'F');
  doc.setFillColor(...colors.success);
  doc.rect(20, yPos, 3, 25, 'F');

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.success);
  doc.text('Total Estimated Back Pay', 28, yPos + 10);
  doc.setFontSize(16);
  doc.text(fmt(data.totalBackPay), 28, yPos + 20);

  addPDFFooter(doc);
  doc.save('back-pay-estimate.pdf');
};
