/**
 * VCS Brand PDF Renderer
 *
 * Shared rendering utilities for all VCS PDF exports. Uses the brand
 * gold/black/cream palette and provides consistent layout primitives.
 *
 * All doctor-facing documents include a "PATIENT-PREPARED" watermark
 * and 38 CFR Part 14 disclaimer on every page.
 */
import type jsPDFType from 'jspdf';
import { PDF_BRAND, type RGBColor } from './pdfColors';
import { DOCTOR_SUMMARY_DISCLAIMER } from '@/utils/bannedPhrases';
import { guardExport, type ExportGuardResult } from '@/utils/exportGuard';

// ── Errors ──────────────────────────────────────────────────────

export class ExportBlockedError extends Error {
  guardResult: ExportGuardResult;
  constructor(result: ExportGuardResult) {
    super(result.message);
    this.name = 'ExportBlockedError';
    this.guardResult = result;
  }
}

export function assertExportClean(text: string): void {
  const result = guardExport(text);
  if (!result.allowed) throw new ExportBlockedError(result);
}

// ── Loader ──────────────────────────────────────────────────────

export const loadJsPDF = async () => {
  const { default: jsPDF } = await import('jspdf');
  return jsPDF;
};

// ── Constants ───────────────────────────────────────────────────

const MARGIN_LEFT = 20;
const MARGIN_RIGHT = 20;
const FOOTER_HEIGHT = 50;

const DISCLAIMER_TEXT = [
  'DISCLAIMER: Generated by Vet Claim Support. Not VA-accredited (38 C.F.R. Part 14).',
  'This document is patient-organized clinical information for educational and personal preparation only.',
  'It does not constitute legal or medical advice, does not file claims, and provides no medical opinions.',
  'Not affiliated with the U.S. Department of Veterans Affairs.',
];

// ── Document Creation ───────────────────────────────────────────

export interface CreatePDFOptions {
  /** Whether to add PATIENT-PREPARED watermark on each page */
  watermark?: boolean;
  /** Whether this is doctor-facing (adds doctor disclaimer) */
  doctorFacing?: boolean;
}

/**
 * Creates a new jsPDF document with VCS brand defaults.
 * Registers afterPage hook for automatic footer + watermark.
 */
export async function createPDFDoc(options: CreatePDFOptions = {}) {
  const JsPDF = await loadJsPDF();
  const doc = new JsPDF({ unit: 'pt', format: 'letter', compress: true });

  // Track page numbers for footer rendering during save
  const state = {
    totalPages: 0,
    watermark: options.watermark ?? false,
    doctorFacing: options.doctorFacing ?? false,
  };

  return { doc, state };
}

/**
 * Finalize the document: add footer/watermark to every page and return blob.
 */
export function finalizePDF(
  doc: jsPDFType,
  state: { totalPages?: number; watermark: boolean; doctorFacing: boolean },
): Blob {
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addBrandFooter(doc, i, totalPages, state.doctorFacing);
    if (state.watermark) {
      addWatermark(doc, 'PATIENT-PREPARED');
    }
  }
  return doc.output('blob');
}

// ── Header ──────────────────────────────────────────────────────

export interface BrandHeaderOptions {
  title: string;
  subtitle?: string;
  date?: Date;
}

/**
 * Adds a branded header with gold title, gold rule, subtitle, and date.
 * Returns the Y position after the header.
 */
export function addBrandHeader(doc: jsPDFType, options: BrandHeaderOptions, yPos: number = 40): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const date = options.date || new Date();

  // Title in gold
  doc.setFontSize(20);
  doc.setTextColor(...PDF_BRAND.goldDark);
  doc.setFont('helvetica', 'bold');
  doc.text(options.title, MARGIN_LEFT, yPos);

  // Gold rule under title
  yPos += 6;
  doc.setDrawColor(...PDF_BRAND.goldMedium);
  doc.setLineWidth(1.5);
  doc.line(MARGIN_LEFT, yPos, pageWidth - MARGIN_RIGHT, yPos);

  yPos += 16;

  // Subtitle
  if (options.subtitle) {
    doc.setFontSize(11);
    doc.setTextColor(...PDF_BRAND.textSecondary);
    doc.setFont('helvetica', 'normal');
    doc.text(options.subtitle, MARGIN_LEFT, yPos);
    yPos += 14;
  }

  // Generated date
  doc.setFontSize(8);
  doc.setTextColor(...PDF_BRAND.textMuted);
  doc.text(`Generated: ${date.toLocaleDateString()} at ${date.toLocaleTimeString()}`, MARGIN_LEFT, yPos);

  return yPos + 16;
}

// ── Footer ──────────────────────────────────────────────────────

function addBrandFooter(doc: jsPDFType, pageNum: number, totalPages: number, doctorFacing: boolean): void {
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  const footerTop = pageHeight - FOOTER_HEIGHT;

  // Dark footer bar
  doc.setFillColor(...PDF_BRAND.black);
  doc.rect(0, footerTop, pageWidth, FOOTER_HEIGHT, 'F');

  // Disclaimer text in white
  doc.setFontSize(6.5);
  doc.setTextColor(...PDF_BRAND.white);
  doc.setFont('helvetica', 'normal');

  let textY = footerTop + 10;
  for (const line of DISCLAIMER_TEXT) {
    doc.text(line, pageWidth / 2, textY, { align: 'center' });
    textY += 8;
  }

  // Doctor-facing extra disclaimer
  if (doctorFacing) {
    doc.setFontSize(6);
    doc.setTextColor(200, 200, 200);
    doc.text(DOCTOR_SUMMARY_DISCLAIMER, pageWidth / 2, textY + 2, {
      align: 'center',
      maxWidth: pageWidth - 60,
    });
  }

  // Page number
  doc.setFontSize(7);
  doc.setTextColor(180, 180, 180);
  doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - MARGIN_RIGHT, footerTop + 10, { align: 'right' });
}

// ── Section Heading ─────────────────────────────────────────────

/**
 * Adds a gold section heading with a gold rule beneath.
 */
export function addSectionHeading(doc: jsPDFType, title: string, yPos: number): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  yPos = checkPageBreak(doc, yPos, 30);

  doc.setFontSize(14);
  doc.setTextColor(...PDF_BRAND.goldDark);
  doc.setFont('helvetica', 'bold');
  doc.text(title, MARGIN_LEFT, yPos);

  yPos += 4;
  doc.setDrawColor(...PDF_BRAND.goldLight);
  doc.setLineWidth(0.75);
  doc.line(MARGIN_LEFT, yPos, pageWidth - MARGIN_RIGHT, yPos);

  return yPos + 12;
}

/**
 * Adds a subsection heading (smaller, dark text).
 */
export function addSubsectionHeading(doc: jsPDFType, title: string, yPos: number): number {
  yPos = checkPageBreak(doc, yPos, 24);
  doc.setFontSize(11);
  doc.setTextColor(...PDF_BRAND.textPrimary);
  doc.setFont('helvetica', 'bold');
  doc.text(title, MARGIN_LEFT, yPos);
  return yPos + 14;
}

// ── Table ───────────────────────────────────────────────────────

export interface TableColumn {
  header: string;
  width: number; // points
  align?: 'left' | 'center' | 'right';
}

export interface TableRow {
  cells: string[];
  bold?: boolean;
}

/**
 * Draws a table with gold header row and clean body rows.
 * Returns yPos after the table.
 */
export function addTable(
  doc: jsPDFType,
  columns: TableColumn[],
  rows: TableRow[],
  yPos: number,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const tableWidth = pageWidth - MARGIN_LEFT - MARGIN_RIGHT;
  const rowHeight = 18;
  const headerHeight = 20;

  yPos = checkPageBreak(doc, yPos, headerHeight + rowHeight * Math.min(rows.length, 3) + 10);

  // Header row
  doc.setFillColor(...PDF_BRAND.goldDark);
  doc.rect(MARGIN_LEFT, yPos, tableWidth, headerHeight, 'F');

  doc.setFontSize(8);
  doc.setTextColor(...PDF_BRAND.white);
  doc.setFont('helvetica', 'bold');

  let x = MARGIN_LEFT + 6;
  for (const col of columns) {
    const textX = col.align === 'right' ? x + col.width - 6 : col.align === 'center' ? x + col.width / 2 : x;
    doc.text(col.header, textX, yPos + 13, { align: col.align || 'left' });
    x += col.width;
  }

  yPos += headerHeight;

  // Body rows
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);

  for (let r = 0; r < rows.length; r++) {
    yPos = checkPageBreak(doc, yPos, rowHeight + 4);

    // Alternate row bg
    if (r % 2 === 0) {
      doc.setFillColor(...PDF_BRAND.cream);
      doc.rect(MARGIN_LEFT, yPos, tableWidth, rowHeight, 'F');
    }

    doc.setTextColor(...PDF_BRAND.textPrimary);
    if (rows[r].bold) doc.setFont('helvetica', 'bold');
    else doc.setFont('helvetica', 'normal');

    x = MARGIN_LEFT + 6;
    for (let c = 0; c < columns.length; c++) {
      const cellText = rows[r].cells[c] || '';
      const col = columns[c];
      // Truncate to fit column
      const maxWidth = col.width - 12;
      const lines = doc.splitTextToSize(cellText, maxWidth);
      const displayText = lines.length > 1 ? lines[0].slice(0, -3) + '...' : lines[0] || '';
      const textX = col.align === 'right' ? x + col.width - 6 : col.align === 'center' ? x + col.width / 2 : x;
      doc.text(displayText, textX, yPos + 12, { align: col.align || 'left' });
      x += col.width;
    }

    yPos += rowHeight;
  }

  // Bottom border
  doc.setDrawColor(...PDF_BRAND.border);
  doc.setLineWidth(0.5);
  doc.line(MARGIN_LEFT, yPos, MARGIN_LEFT + tableWidth, yPos);

  return yPos + 8;
}

// ── Highlight Box ───────────────────────────────────────────────

/**
 * Draws a cream-colored highlight box with gold left border.
 * Supports multi-line text with auto-wrapping.
 */
export function addHighlightBox(
  doc: jsPDFType,
  text: string,
  yPos: number,
  options?: { label?: string; type?: 'info' | 'success' | 'warning' | 'danger' },
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const boxWidth = pageWidth - MARGIN_LEFT - MARGIN_RIGHT;
  const maxTextWidth = boxWidth - 20;

  const lines = doc.splitTextToSize(text, maxTextWidth);
  const labelHeight = options?.label ? 14 : 0;
  const boxHeight = lines.length * 10 + 16 + labelHeight;

  yPos = checkPageBreak(doc, yPos, boxHeight + 4);

  // Background
  doc.setFillColor(...PDF_BRAND.cream);
  doc.roundedRect(MARGIN_LEFT, yPos, boxWidth, boxHeight, 3, 3, 'F');

  // Left accent bar
  const accentColor: RGBColor =
    options?.type === 'success' ? PDF_BRAND.success :
    options?.type === 'warning' ? PDF_BRAND.warning :
    options?.type === 'danger' ? PDF_BRAND.danger :
    PDF_BRAND.goldMedium;
  doc.setFillColor(...accentColor);
  doc.rect(MARGIN_LEFT, yPos, 4, boxHeight, 'F');

  let textY = yPos + 12;

  // Optional label
  if (options?.label) {
    doc.setFontSize(8);
    doc.setTextColor(...accentColor);
    doc.setFont('helvetica', 'bold');
    doc.text(options.label.toUpperCase(), MARGIN_LEFT + 14, textY);
    textY += 12;
  }

  // Body text
  doc.setFontSize(8.5);
  doc.setTextColor(...PDF_BRAND.textPrimary);
  doc.setFont('helvetica', 'normal');
  for (const line of lines) {
    doc.text(line, MARGIN_LEFT + 14, textY);
    textY += 10;
  }

  return yPos + boxHeight + 6;
}

// ── Stat Box ────────────────────────────────────────────────────

export interface StatItem {
  label: string;
  value: string;
}

/**
 * Draws a row of stat boxes (value + label pairs) in cream cards.
 */
export function addStatBox(doc: jsPDFType, stats: StatItem[], yPos: number): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const totalWidth = pageWidth - MARGIN_LEFT - MARGIN_RIGHT;
  const boxWidth = (totalWidth - (stats.length - 1) * 8) / stats.length;
  const boxHeight = 44;

  yPos = checkPageBreak(doc, yPos, boxHeight + 8);

  for (let i = 0; i < stats.length; i++) {
    const x = MARGIN_LEFT + i * (boxWidth + 8);

    // Card bg
    doc.setFillColor(...PDF_BRAND.cream);
    doc.roundedRect(x, yPos, boxWidth, boxHeight, 3, 3, 'F');

    // Gold top accent
    doc.setFillColor(...PDF_BRAND.goldMedium);
    doc.rect(x, yPos, boxWidth, 3, 'F');

    // Value
    doc.setFontSize(16);
    doc.setTextColor(...PDF_BRAND.goldDark);
    doc.setFont('helvetica', 'bold');
    doc.text(stats[i].value, x + boxWidth / 2, yPos + 22, { align: 'center' });

    // Label
    doc.setFontSize(7);
    doc.setTextColor(...PDF_BRAND.textSecondary);
    doc.setFont('helvetica', 'normal');
    doc.text(stats[i].label, x + boxWidth / 2, yPos + 36, { align: 'center' });
  }

  return yPos + boxHeight + 10;
}

// ── Key-Value Pair ──────────────────────────────────────────────

/**
 * Renders a label: value pair on a single line.
 */
export function addKeyValue(doc: jsPDFType, label: string, value: string, yPos: number): number {
  yPos = checkPageBreak(doc, yPos, 14);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_BRAND.textSecondary);
  doc.text(`${label}:`, MARGIN_LEFT, yPos);

  const labelWidth = doc.getTextWidth(`${label}: `);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...PDF_BRAND.textPrimary);
  doc.text(value || 'Not provided', MARGIN_LEFT + labelWidth + 2, yPos);

  return yPos + 13;
}

// ── Bullet List ─────────────────────────────────────────────────

/**
 * Renders a bulleted list of items.
 */
export function addBulletList(doc: jsPDFType, items: string[], yPos: number): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...PDF_BRAND.textPrimary);

  for (const item of items) {
    yPos = checkPageBreak(doc, yPos, 12);
    doc.text('\u2022', MARGIN_LEFT + 4, yPos);
    const lines = doc.splitTextToSize(item, pageWidth - MARGIN_LEFT - MARGIN_RIGHT - 20);
    for (const line of lines) {
      doc.text(line, MARGIN_LEFT + 14, yPos);
      yPos += 11;
    }
  }

  return yPos + 2;
}

// ── Self-Reported Data Label ────────────────────────────────────

/**
 * Adds the standard "(from veteran's self-reported logs)" label.
 */
export function addSelfReportedLabel(doc: jsPDFType, yPos: number): number {
  doc.setFontSize(7);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...PDF_BRAND.textMuted);
  doc.text('(from veteran\'s self-reported logs)', MARGIN_LEFT, yPos);
  return yPos + 10;
}

// ── Not Yet Documented ──────────────────────────────────────────

/**
 * Renders a "Not yet documented" placeholder for missing data.
 */
export function addNotYetDocumented(doc: jsPDFType, section: string, yPos: number): number {
  yPos = checkPageBreak(doc, yPos, 30);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...PDF_BRAND.textMuted);
  doc.text(`${section}: Not yet documented`, MARGIN_LEFT + 4, yPos);
  return yPos + 14;
}

// ── Watermark ───────────────────────────────────────────────────

function addWatermark(doc: jsPDFType, text: string): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.saveGraphicsState();
  doc.setFontSize(48);
  doc.setTextColor(...PDF_BRAND.watermark);
  doc.setFont('helvetica', 'bold');

  // Rotate and center the watermark
  const centerX = pageWidth / 2;
  const centerY = pageHeight / 2;

  // jsPDF text rotation via transform
  doc.text(text, centerX, centerY, {
    align: 'center',
    angle: 45,
  });
  doc.restoreGraphicsState();
}

// ── Page Break Helper ───────────────────────────────────────────

/**
 * Checks if there's enough room for the next content block.
 * If not, adds a page and returns the starting Y.
 */
export function checkPageBreak(doc: jsPDFType, yPos: number, neededHeight: number = 40): number {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (yPos + neededHeight > pageHeight - FOOTER_HEIGHT - 10) {
    doc.addPage();
    return 40; // top margin on new page
  }
  return yPos;
}

// ── Safe Date Helper ────────────────────────────────────────────

export function safeDate(dateStr: string | undefined | null): string {
  if (!dateStr) return 'N/A';
  const d = new Date(dateStr);
  return isNaN(d.getTime()) ? 'N/A' : d.toLocaleDateString();
}

// ── Spacing ─────────────────────────────────────────────────────

export function addSpacer(doc: jsPDFType, yPos: number, height: number = 8): number {
  return checkPageBreak(doc, yPos + height);
}
